---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(MatchIt)
library(tidyverse)
library(DescTools) 
library(broom)
library(scales) # for comma in ggplot
library(cowplot)
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r contractor_capability, include=FALSE}

# Number of projects with positive delay before QuickPay

delay_before_qp=reg_df_subset[post_t==0 & delay>0][,
                         .(num_projs_delayed=n_distinct(contract_award_unique_key)),
                       by='recipient_duns']


num_proj_before_qp=reg_df_subset[post_t==0][,
                         .(num_projs=n_distinct(contract_award_unique_key)),
                       by='recipient_duns']

contractor_capability=merge(delay_before_qp,
                            num_proj_before_qp,
         by='recipient_duns',
         all.y=T)

contractor_capability=contractor_capability[!is.na(recipient_duns)]
# Set na values for num_projs_delayed to be zero 
contractor_capability[is.na(contractor_capability)]=0
contractor_capability[,frac_delayed:=num_projs_delayed/num_projs]
```


```{r merge_with_reg, include=FALSE}
reg_df_subset[, two_digit_psc:=substr(product_or_service_code,1,2)]
reg_df_subset[, two_digit_naics:=substr(naics_code,1,2)]

reg_df_subset=merge(reg_df_subset,
                    contractor_capability[,c('recipient_duns',
                                             'frac_delayed')],
                    by='recipient_duns',
                    all.x=T)
```


```{r matching, include=FALSE}
set.seed(190)

input=na.omit(reg_df_subset,
                            cols=c('product_or_service_code',
                                'awarding_sub_agency_code',
                                'naics_code',
                                'wins_project_quarter_stage',
                                'wins_number_of_offers_received',
                                'winsorized_initial_duration_in_days_i',
                                'winsorized_initial_budget_i',
                                'frac_delayed'))

matched_df_1=match.data(matchit(treat_new~frac_delayed+
                                  as.factor(awarding_sub_agency_code)+
                                  as.factor(two_digit_naics)+
                                  as.factor(action_date_year_quarter)+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                                data=input,
                                cutpoints= list(frac_delayed=5,
                                                winsorized_initial_duration_in_days_i = 5,
                                                winsorized_initial_budget_i = 5,
                                                wins_number_of_offers_received=5),
                                method='cem'))

matched_df_2=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      method='nearest',
                      ratio=1))

matched_df_3=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      method='nearest',
                      ratio=2))

matched_df_4=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      method='nearest',
                      ratio=3))

matched_df_5=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      method='nearest',
                      ratio=4))

matched_df_6=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      distance='mahalanobis'))

matched_df_7=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      distance='lasso'))

matched_df_8=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      distance='rpart'))

matched_df_9=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      caliper=0.2))

matched_df_10=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      caliper=0.3))

matched_df_11=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      caliper=0.4))

matched_df_12=match.data(matchit(treat_new~frac_delayed+
                                  winsorized_initial_duration_in_days_i+
                                  winsorized_initial_budget_i+
                                  wins_number_of_offers_received,
                      data=input,
                      exact=~as.factor(awarding_sub_agency_code)+
                                as.factor(two_digit_psc)+
                               as.factor(two_digit_naics)+
                                as.factor(action_date_year_quarter),
                      caliper=0.5))
```

```{r regs, include=FALSE}
df_list=list(matched_df_1,
             matched_df_2,
             matched_df_3,
             matched_df_4,
             matched_df_5,
             matched_df_6,
             matched_df_7,
             matched_df_8,
             matched_df_9,
             matched_df_10,
             matched_df_11,
             matched_df_12)

reg_list=list()
estimate_percentage_delay=list()
sample_size_percentage_delay=list()

i=1
for(df in df_list){
  print(i)
  setDT(df)
  df[,wins_percentage_delay:=100*Winsorize(percentage_delay,probs=c(0.025,0.975),na.rm=T)]
  df[,winsorized_delay:=Winsorize(delay,probs=c(0.025,0.975),na.rm=T)]
  m=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                          data=df, 
                          weights=~weights,
                          cluster=~contract_award_unique_key)
  
  estimate_percentage_delay[[i]]=setDT(tidy(m, conf.int=T))[term=='treat_new:post_t']
  sample_size_percentage_delay[[i]]=glance(m)$nobs
  reg_list[[i]]=m
  i=i+1
}
```

```{r export_tables, echo=FALSE, results='asis'}
setFixest_dict(dict=c("treat_new" = "Treat",
               "post_t"="Post",
               "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
               "log(1+winsorized_initial_budget_i)"="Initial budget",
               "wins_number_of_offers_received"="Number of offers received",
               "log(wins_project_quarter_stage)"="Project stage",
               "naics_code"="NAICS code",
               "product_or_service_code"="Task code",
               "action_date_year_quarter"="Time",
               "contract_award_unique_key"="Project ID"))

etable(reg_list[1:7],
       tex=TRUE,
       fontsize = "tiny",
       drop=c("Initial duration",
              "Initial budget",
              "Number of offers received",
              "Project stage"),
       digits='r2',
       digits.stats = 2
)

etable(reg_list[8:12],
       tex=TRUE,
       fontsize = "tiny",
       drop=c("Initial duration",
              "Initial budget",
              "Number of offers received",
              "Project stage"),
       digits='r2',
       digits.stats = 2)
```

