---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r get_action_types, include=FALSE}
full_df=fread('~/Dropbox/data_quickpay/qp_data/qp_data_fy10_to_fy18.csv',
              select = c('contract_award_unique_key',
                       'action_date',
                       'action_type_code'))

full_df_sub=full_df[contract_award_unique_key%in%reg_df_subset$contract_award_unique_key &
                  action_date<=max(reg_df_subset$action_date_year_quarter)]
```

```{r exclude_action_types, include=FALSE}
projects_with_scope_action_codes=unique(full_df_sub[action_type_code%in%
                                                      c("D","A","L","G")]$contract_award_unique_key)


# Remove all codes except "" and "M"
codes_to_remove=setdiff(unique(full_df_sub$action_type_code),c("","M"))
projects_with_codes_other_than_m=unique(full_df_sub[action_type_code%in%
                                                      codes_to_remove]$contract_award_unique_key)


# Contracts: 
# A = ADDITIONAL WORK (NEW AGREEMENT, JUSTIFICATION REQUIRED)
# B = SUPPLEMENTAL AGREEMENT FOR WORK WITHIN SCOPE
# C = FUNDING ONLY ACTION
# D = CHANGE ORDER
# E = TERMINATE FOR DEFAULT (COMPLETE OR PARTIAL)
# F = TERMINATE FOR CONVENIENCE (COMPLETE OR PARTIAL)
# G = EXERCISE AN OPTION H = DEFINITIZE LETTER CONTRACT
# J = NOVATION AGREEMENT
# K = CLOSE OUT
# L = DEFINITIZE CHANGE ORDER
# M = OTHER ADMINISTRATIVE ACTION
# N = LEGAL CONTRACT CANCELLATION
# P = REREPRESENTATION OF NON-NOVATED MERGER/ACQUISITION
# R = REREPRESENTATION
# S = CHANGE PIID #No project in our sample has this code
# T = TRANSFER ACTION
# V = UNIQUE ENTITY ID (DUNS) OR LEGAL BUSINESS NAME CHANGE - NON-NOVATION
# W = ENTITY ADDRESS CHANGE
# X = TERMINATE FOR CAUSE
# Y = ADD SUBCONTRACT PLAN
```

```{r baseline_regressions, include=FALSE, warning=FALSE}
m0=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received+
                            post_t,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_scope_action_codes)])


m1=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_scope_action_codes)])

m2=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_scope_action_codes)])


m3=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_scope_action_codes)])

m4=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
                            awarding_sub_agency_code,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_scope_action_codes)])

exclude_scope_action_types=list(m2,m3,m4)
```

```{r baseline_regressions, include=FALSE, warning=FALSE}
m0=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received+
                            post_t,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_codes_other_than_m)])


m1=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_codes_other_than_m)])

m2=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_codes_other_than_m)])


m3=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_codes_other_than_m)])

m4=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
                            awarding_sub_agency_code,
                          cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(contract_award_unique_key%in%projects_with_codes_other_than_m)])

exclude_other_action_types=list(m2,m3,m4)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percentage delay",
                      "post_t"="Post",
                      "treat_new"="Treat",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))

etable(exclude_scope_action_types,
       exclude_other_action_types,
       digits='r2',
       digits.stats = 2,
       title="Excluding projects with certain action types",
       headers=list("Exclude action types D, A, L, and G"=length(exclude_scope_action_types),
                    "Exclude all action types except M"=length(exclude_other_action_types)),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex=style.tex(fixef.title = "",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "",
                           model.title = "",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Sample restricted to projects with only some action types. Controls include project stage, initial duration, initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```
