---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools)
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r delay_rates,include=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

delay_rates=list(m1,m2,m3)
```

```{r positive_delay_setup, include=FALSE}
reg_df_subset[,positive_delay:=ifelse(delay>0,1,0)]

reg_df_subset_positive=subset(reg_df_subset,delay>0)
reg_df_subset_positive[,wins_percentage_delay:=Winsorize(100*percentage_delay,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset_positive[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,
                                                              probs=c(0.05,0.95),
                                na.rm=T)]

reg_df_subset_positive[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i
reg_df_subset_positive[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset_positive[,wins_number_of_offers_received:=
                    Winsorize(number_of_offers_received,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]
```

```{r positive_delay_logit, include=FALSE}
m1=feglm(positive_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2=feglm(positive_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feglm(positive_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

positive_delay_logit=list(m1,m2,m3)
```

```{r conditional_delay_rates,include=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m2=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m3=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

conditional_delay_rates=list(m1,m2,m3)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="Post",
                      "treat_new"="Treat",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))

etable(delay_rates,
       positive_delay_logit,
       conditional_delay_rates,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Baseline diff-in-diff effect",
       headers=list("Average treatment effect"=length(delay_rates),
                    "Delay likelihood and conditional ATE"=length(positive_delay_logit)+
                                                           length(conditional_delay_rates)),
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex=style.tex(fixef.title = "",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "",
                           model.title = "",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```


