---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(quantreg)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools)
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))

non_zero_delays=reg_df_subset[delay!=0]
non_zero_delays[,winsorized_delay:=Winsorize(delay,
                                             probs=c(0.05,0.95),
                                             na.rm=T)]

non_zero_delays[,wins_percentage_delay:=Winsorize(100*percentage_delay,
                                                  probs=c(0.05,0.95),
                                                  na.rm=T)]

```

```{r}
ls_fl_quantiles <- seq(0.05,0.9,0.1)
fit_quantiles <- rq(wins_percentage_delay ~ treat_new+
                     post_t:treat_new+
                      post_t+
                     log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received,
               tau = ls_fl_quantiles,
               data = non_zero_delays)

plot(fit_quantiles,
     parm=8,
     ols=T,
     ylim=c(-5,30),
     xlim=c(0.05,0.95),
     xlab="Quantile",
     ylab="Treatment effect \n (Percentage delay rate)",
     mar=c(5.1, 5.1, 2.1, 2.1))

```

```{r}
# Takes a while to run
sum_qt=summary(fit_quantiles, 
               se = "boot",
               cluster=non_zero_delays$contract_award_unique_key)
```

```{r}
plot(sum_qt,
     parm=8,
     ols=T,
     cex=1,
     pch=17, #shape
     col=c('black','lightgray'),
     ylim=c(-5,40),
     xlab="Quantile",
     ylab="Treatment effect  \n (Percentage delay rate)",
     mar=c(5.1, 6.1, 2.1, 2.1), # Need to expand margins to show labels
     main="")
```

```{r}
m=feols(wins_percentage_delay ~ treat_new+
          post_t:treat_new+
       log(wins_project_quarter_stage)+
              log(1+winsorized_initial_duration_in_days_i)+
              log(1+winsorized_initial_budget_i)+
              wins_number_of_offers_received+
              post_t:log(1+winsorized_initial_duration_in_days_i)+
             post_t:log(1+winsorized_initial_budget_i)+
              post_t:wins_number_of_offers_received+
         post_t,
       cluster=~contract_award_unique_key,
      data = non_zero_delays)

```

