---
title: "Non C8A participants"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(tidyverse)
library(DescTools)
library(fixest)
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))

data_folder='~/Dropbox/data_quickpay/qp_data/'
df_first_reported=fread(paste0(data_folder,'qp_data_first_reported.csv'))

```

```{r 8a_participants, include=FALSE}
c8a_participants=df_first_reported[,c('contract_award_unique_key',
                                      'c8a_program_participant',
                                      'type_of_set_aside')]

reg_df_subset=merge(reg_df_subset,
                    c8a_participants,
                    by='contract_award_unique_key',
                    all.x=T)
```

## Non-C8A participants

```{r non_c8a_regs, include=FALSE,warning=FALSE,message=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                     post_t:treat_new+
                     post_t,
                  cluster=~contract_award_unique_key, # clustered at project level
                  data=reg_df_subset[c8a_program_participant=="f"])

m2=feols(wins_percentage_delay~treat_new+
                           post_t:treat_new+
                           post_t+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"])

m3=feols(wins_percentage_delay~treat_new+
                             post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"])

m4=feols(wins_percentage_delay~treat_new+
                              post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"])

m5=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"])

non_c8a=list(m4,m5)
```

## No set aside used

```{r no_set_aside, include=FALSE,warning=FALSE,message=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                     post_t:treat_new+
                     post_t,
                  cluster=~contract_award_unique_key, # clustered at project level
                  data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])

m2=feols(wins_percentage_delay~treat_new+
                           post_t:treat_new+
                           post_t+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])

m3=feols(wins_percentage_delay~treat_new+
                             post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])

m4=feols(wins_percentage_delay~treat_new+
                              post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])

m5=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])

no_set_aside_used=list(m4,m5)
```

## Started before QuickPay

```{r before_qp, include=FALSE}
projects_started_before_qp=unique(reg_df_subset[initial_start_date<=
                                                  as.Date('2011-04-27')]$contract_award_unique_key)


m4=feols(wins_percentage_delay~treat_new+
                              post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[contract_award_unique_key%in%
                                               projects_started_before_qp])

m5=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[contract_award_unique_key%in%
                                               projects_started_before_qp])

projects_before_qp=list(m4,m5)
```

## JOBS act

* Jobs act = 1 if Date> Sept 30, 2010
* Jobs act was announced on Sept 27, 2010
* This variable is zero for only three quarters in our study period: Mar 31, 2010; June 30, 2010; and Sept 30, 2010.

```{r jobs_act,include=FALSE,warning=FALSE,message=FALSE}
reg_df_subset[,jobs_act:=ifelse(action_date_year_quarter>as.Date('2010-09-30'),1,0)]

m1=feols(wins_percentage_delay~treat_new+
                            treat_new:jobs_act+
                     post_t:treat_new+
                     post_t+
                    jobs_act,
                  cluster=~contract_award_unique_key, # clustered at project level
                  data=reg_df_subset)

m2=feols(wins_percentage_delay~treat_new+
                            treat_new:jobs_act+
                           post_t:treat_new+
                           post_t+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feols(wins_percentage_delay~treat_new+
                            treat_new:jobs_act+
                             post_t:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m4=feols(wins_percentage_delay~treat_new+
                              post_t:treat_new+
                            treat_new:jobs_act+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m5=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            treat_new:jobs_act+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

jobs_act_regs=list(m4,m5)
```

```{r export_results, echo=FALSE,results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percentage delay",
                      "post_t"="Post",
                      "treat_new"="Treat",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task code",
                      "action_date_year_quarter"="Time",
                      "naics_code"="NAICS",
                      "jobs_act"="JOBS Act"
                      ))

etable(non_c8a,
       no_set_aside_used,
       projects_before_qp,
       jobs_act_regs,
       digits='r2',
       fontsize = 'tiny',
       title="Alternative explanations",
       headers=list("Excluding C8A participant"=2, 
                    "Excluding set-aside used"=2,
                    "Excluding projects that started after QuickPay"=2,
                    "JOBS act"=2),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       notes="Sample restricted to projects whose contractors are not C8A participants. Controls include project stage, initial duration, initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)

etable(non_c8a,
       digits='r2',
       title="Non-C8A participants",
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       notes="Sample restricted to projects whose contractors are not C8A participants. Controls include project stage, initial duration, initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)

etable(jobs_act_regs,
       title="JOBS act",
       digits='r2',
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       notes="Controls include project stage, initial duration, initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)

etable(no_set_aside_used,
       title="No set aside used",
       digits='r2',
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       notes="Sample restricted to projects that did not use any set aside in the solicitation process. Controls include project stage, initial duration, initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```
