---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(openxlsx)
library(tidyverse)
library(dplyr)
library(pryr)
library(lfe) # linear fixed effects 
library(DescTools) 
library(zoo) # for year quarter
library(stargazer)
library(broom)
library(fixest)
library(data.table)
library(scales)
library(coefplot)
library(MatchIt)
library(pBrackets)
library(grid)
library(fixest)
library(xtable)
```

```{r set_path_for_exporting, include=FALSE}
tables_folder='~/Desktop/Research/QuickPay/paper/Tables/percentage_delay_rate'
figures_folder='~/Desktop/Research/QuickPay/paper/Figures'
data_folder='~/Dropbox/data_quickpay/qp_data/'
```

```{r read_data, include=FALSE}
# Keep only projects whose start dates match with API one
projects_to_keep=fread(paste0(data_folder,'projects_to_keep.csv'))

# read quarterly resampled data
df=fread(paste0(data_folder,'resampled_qp_data/qp_resampled_data_fy10_to_fy12_with_zero_obs.csv'))
# specify date columns
date_cols=c("action_date_year_quarter","last_reported_start_date","last_reported_end_date")
df[,(date_cols):= lapply(.SD, as.Date), .SDcols = date_cols]

df[,api_projects:=ifelse(contract_award_unique_key%in%projects_to_keep$contract_award_unique_key,1,0)]

# restrict to quarter ending June 30, 2012
df=subset(df,as.Date(action_date_year_quarter)<as.Date('2012-07-01')&
          api_projects==1)

# data is truncated at July 1, 2012 -- 
# so quarter ending Sept 30, 2012 will only have values as of July 1, 2012

df_first_reported=fread(paste0(data_folder,'qp_data_first_reported.csv'))
# contains time-invariant contract characteristics -- info when contract first appeared in the data

```

```{r assign_variables_1, include=FALSE}
# Assign variables: Delay, Winsorized Delay, Post_t, Treat_i

# some projects have action dates beyond project end date 
# some could indicate projects that ended in the beginning of a quarter -- so taking 90 days difference
# dropping these -- likely admin/documentation changes

df[,diff_end_date_and_action_date:=as.numeric(last_reported_end_date-action_date_year_quarter)]
# to ensure project ended sometime this quarter
df=subset(df,diff_end_date_and_action_date>-90)


# AD: 2015-06-30; End Date: 2015-03-31

# sort by contract id and date 
df=df[order(contract_award_unique_key,
            action_date_year_quarter)]

# determine quarter-to-quarter delay
df[,delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_end_date-lag(last_reported_end_date,1),NaN)]

# winsorize quarter-to-quarter delay
df[,winsorized_delay:=Winsorize(delay,
                                probs=c(0.05,0.95),
                                na.rm=TRUE)]

#Post_t: A dummy that period t is post-treatment
df[,post_t:=ifelse(action_date_year_quarter>as.Date("2011-04-27"),1,0)]
# quickpay implemented on 27 April 2011. So all quarters starting 30 June 2011 will be in post-period

#Treat_i: A dummy that contract i is in the treatment group
df[,treat_i:=ifelse(business_type=="S",1,0)]
# quickpay was implemented for small business contracts

# determine quarter-to-quarter overrun
df[,overrun:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_budget-lag(last_reported_budget,1),NaN)]

# winsorize quarter-to-quarter overrun
df[,winsorized_overrun:=Winsorize(overrun,
                                probs=c(0.05,0.95),
                                na.rm=TRUE)]

df[,percentage_overrun:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1) &
                                     lag(last_reported_budget,1)>0,
         overrun/lag(last_reported_budget,1),
         NaN)]
```

```{r assign_variables_2, include=FALSE}

# ContractFinancing_i
df_first_reported[,contract_financing_i:=ifelse(!is.null(contract_financing_code)&
                                       !contract_financing_code%in%c("Z", ""),1,0)]

# Competition_i
df_first_reported[,competitively_awarded_i:=ifelse(!extent_competed_code%in%c("G","B", "C"),1,0)]
df_first_reported[,initial_end_date:=period_of_performance_current_end_date]
df_first_reported[,initial_start_date:=period_of_performance_start_date]

# InitialDuration_i
df_first_reported[,initial_duration_in_days_i:=
                    as.numeric(
                    as.Date(initial_end_date)-
                    as.Date(initial_start_date))]

select_cols=c("contract_award_unique_key",
              "naics_code",
              "product_or_service_code",
              "number_of_offers_received",
              "performance_based_service_acquisition_code",
              "contract_financing_i",
              "competitively_awarded_i",
              "recipient_duns",
              "initial_end_date",
              "initial_start_date",
              "initial_duration_in_days_i",
              "base_and_all_options_value",
              "awarding_sub_agency_code")

# not necessary but speed efficient to set keys
setkey(df_first_reported[,..select_cols],
       contract_award_unique_key)
setkey(df,contract_award_unique_key)
```

```{r combine_dfs, include=FALSE}
# Combine all variables into dataframe needed for regression 
reg_df=merge(df,
             df_first_reported[,..select_cols],
             all.x = TRUE, # keep values in df, add columns of df_first_reported_cols
             by=c("contract_award_unique_key"))

reg_df[,initial_start_date:=as.Date(initial_start_date)]
reg_df[,initial_end_date:=as.Date(initial_end_date)]
reg_df[,action_date_year_quarter:=as.Date(action_date_year_quarter)]

reg_df[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i

reg_df[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df[,wins_number_of_offers_received:=Winsorize(number_of_offers_received,
                                             probs=c(0.05,0.95),
                                             na.rm=T)]

# sort by contract id and date (just to be doubly sure)
reg_df=reg_df[order(contract_award_unique_key,
            action_date_year_quarter)]

```

```{r percentage_delay,include=FALSE}

reg_df[,last_reported_duration:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),
                                      as.numeric(lag(last_reported_end_date,1)-initial_start_date),
                                      initial_duration_in_days_i)]

# "period_of_performance_start_date" here comes from first reported info
# So it is the actual start date for a project
# get project duration as of last quarter in the denominator
reg_df[,percentage_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),
         delay/last_reported_duration,
         NaN)]

reg_df[,wins_percentage_delay:=Winsorize(100*percentage_delay,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

# time spent in the project so far/total time of the project
# if project was active in previous quarter
reg_df[,project_quarter_stage:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),as.numeric(lag(action_date_year_quarter,1)-initial_start_date)/as.numeric(lag(last_reported_end_date,1)-initial_start_date),NaN)]

# (action_date_year_quarter-90) to get beginning of the quarter

reg_df[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]
```


```{r cumulative_delay, include=FALSE}
reg_df=reg_df[order(contract_award_unique_key,
            action_date_year_quarter)]

reg_df[,cumulative_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_end_date-initial_end_date,NaN)]


reg_df[,wins_cumulative_delay:=Winsorize(cumulative_delay,
                                probs=c(0.05,0.95),
                                na.rm=TRUE)]

reg_df[,pc_cumulative_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  100*(cumulative_delay/initial_duration_in_days_i),NaN)]


reg_df[,wins_pc_cumulative_delay:=Winsorize(pc_cumulative_delay,
                                probs=c(0.05,0.95),
                                na.rm=TRUE)]
```

```{r remove_cols, include=FALSE}
reg_df[,diff_end_date_and_action_date:=NULL]
reg_df[,initial_end_date:=NULL]
reg_df[,api_projects:=NULL]
reg_df[,last_reported_start_date:=NULL]
reg_df[,last_reported_end_date:=NULL]            
reg_df[,last_reported_budget:=NULL]
```

```{r clean_control,include=FALSE}
small_contractors=unique(subset(reg_df,treat_i==1)$recipient_duns)
large_contractors=unique(subset(reg_df,treat_i==0)$recipient_duns)

reg_df[,treat_new:=case_when(treat_i==1 ~ 1,
                             treat_i==0 & !(recipient_duns%in%small_contractors)~0,
                             treat_i==0 & recipient_duns%in%small_contractors~NaN)]

# Small project & contractor does not hold any large project at any point == 1
# Small project & contractor holds a large project at any point == 0
# Large project & contractor does not hold any small project at any point == 0 [Clean control]
# Large project & contractor holds a small project at any point == NaN

reg_df[,treat_only_small:=case_when(treat_i==1 & !(recipient_duns%in%large_contractors)~1,
                                    treat_i==1 & recipient_duns%in%large_contractors~0,
                                    treat_i==0 & !(recipient_duns%in%small_contractors)~0,
                                    treat_i==0 & recipient_duns%in%small_contractors~NaN)]

# Small project & contractor holds large project at any point == 1
reg_df[,treat_small_with_large_new:=case_when(treat_i==1 & !(recipient_duns%in%large_contractors)~0,
                                    treat_i==1 & recipient_duns%in%large_contractors~1,
                                    treat_i==0 & !(recipient_duns%in%small_contractors)~0,
                                    treat_i==0 & recipient_duns%in%small_contractors~NaN)]
       
# already adjusted above, but to be super cautius!
reg_df_subset=subset(reg_df,!(treat_i==0 & recipient_duns%in%small_contractors))

# (action_date_year_quarter-90) to get beginning of the quarter
reg_df_subset[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i
reg_df_subset[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset[,wins_number_of_offers_received:=
                    Winsorize(number_of_offers_received,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]
```

```{r plot,echo=FALSE, results='asis'}

mean_delay=reg_df_subset[!is.na(wins_cumulative_delay) 
                  & action_date_year_quarter<=as.Date('2012-06-30'), 
              .(avg_delay=mean(wins_cumulative_delay),
                se_delay=sd(wins_cumulative_delay,na.rm=T)/sqrt(.N)
                ),  
              by = c('action_date_year_quarter','treat_new')]
mean_delay[,year_quarter:=format(action_date_year_quarter,"%Y-%b")]
mean_delay=mean_delay[order(action_date_year_quarter,treat_new)]

pre_qp_mean_small=mean(subset(mean_delay,
                         action_date_year_quarter<=as.Date('2011-04-27') &
                           treat_new==1)$avg_delay,na.rm=T)
pre_qp_mean_large=mean(subset(mean_delay,
                              action_date_year_quarter<=as.Date('2011-04-27') &
                                treat_new==0)$avg_delay,na.rm=T)

mean_delay[,demeaned_delay:=ifelse(treat_new==1,
                                   avg_delay-pre_qp_mean_small,
                                   avg_delay-pre_qp_mean_large)]

mean_delay[,business_type:=ifelse(treat_new==1,"S","O")]

ggplot(mean_delay, aes(x=year_quarter,
                       y=demeaned_delay, 
                       group = business_type))+
  geom_point(aes(shape=business_type),size=1.5)+
  geom_errorbar(aes(ymin=demeaned_delay-1.96*se_delay, 
                    ymax=demeaned_delay+1.96*se_delay), 
                colour="black", 
                width=.1) +
  geom_line(aes(linetype=business_type, color=business_type),alpha=0.7) +    
  scale_x_discrete(limits=mean_delay$year_quarter)+
  geom_vline(xintercept =10.2,alpha=0.8,linewidth=0.15,linetype="solid")+
  theme_minimal()+
  labs(x="Time", 
       y = "Average cumulative delay rate (in days)")+
  scale_linetype_manual(name  ="",
                        breaks=c("S", "O"),
                        labels=c("Treated","Control"),
                        values=c("solid","dashed"))+
  scale_color_manual(name  ="",
                     breaks=c("S", "O"),
                     labels=c("Treated","Control"),
                     values=c('black','black'))+
  scale_shape_manual(name  ="",
                     breaks=c("S", "O"),
                     labels=c("Treated","Control"),
                     values=c(16,17))+
  theme(axis.text.x = element_text(angle = 90),
        axis.line = element_blank(),
        panel.border = element_rect(fill=NA),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.text = element_text(size=11),
        legend.position="bottom",
        legend.key.width=unit(2.5,"cm"))
```

```{r delay_rates,include=FALSE}
m1=feols(wins_cumulative_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2=feols(wins_cumulative_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feols(wins_cumulative_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

cumulative_delay=list(m1,m2,m3)
```



```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_cumulative_delay"="Cumulative delay rate (in days)",
                      "wins_pc_cumulative_delay"="Cumulative delay rate/Initial duration (pp)",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="Post",
                      "treat_new"="Treat",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))


etable(cumulative_delay,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Baseline diff-in-diff effect",
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex=style.tex(fixef.title = "",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "",
                           model.title = "",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```


