---
title: "Competition -- Contractor Experience"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array,makecell}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))

reg_df_subset=reg_df_subset[!(initial_start_date>as.Date('2011-04-27') 
                              & post_t==0)]

reg_df_subset=reg_df_subset[!is.na(recipient_duns)]
```

```{r define_var, include=FALSE}

# Number of projects held by a contractor in a given quarter
num_proj_per_contractor_df=reg_df_subset[,
                .(num_projects=
                    n_distinct(contract_award_unique_key)),
              by=c('recipient_duns',
                   'action_date_year_quarter')]

# Number of projects of a given task type held by a contractor in a given quarter
num_proj_same_task_df=reg_df_subset[,
                .(num_projects_same_task=
                    n_distinct(contract_award_unique_key)),
              by=c('recipient_duns',
                   'product_or_service_code',
                   'action_date_year_quarter')]

# Merge the two datasets
num_proj_same_task_df=merge(num_proj_same_task_df,
                            num_proj_per_contractor_df,
                            by=c('recipient_duns',
                                 'action_date_year_quarter'),
                            all.x=T)

# Proportion of projects of same task type held by a contractor in a given quarter
#num_proj_same_task_df[,prop_projects_same_task:=num_projects_same_task/num_projects]

num_proj_same_task_df=num_proj_same_task_df[order(recipient_duns,
                                                   product_or_service_code,
                                                   action_date_year_quarter)]
```

```{r get_lags, include=FALSE}
###########################################
# LAG OF 1
##########################################
# If same contractor last quarter + same task last quarter, take lag value. Else take zero.
# Zero can indicate:
# 1. Same contractor last quarter + different task last quarter, OR
# 2. Different contractor last quarter i.e., contractor is new entrant
num_proj_same_task_df[,num_projects_same_task_lag_1:=ifelse(recipient_duns==
                                                                 lag(recipient_duns)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code),
                                                            lag(num_projects_same_task),
                                                            0)]

num_proj_same_task_df[,num_projects_lag_1:=ifelse(recipient_duns==
                                                                 lag(recipient_duns)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code),
                                                            lag(num_projects),
                                                            0)]
###########################################
# LAG OF 2
##########################################
# If same contractor second-to-last quarter + same task second-to-last quarter, take lag-2 value. Else take zero.
# Zero can indicate:
# 1. Same contractor second-to-last quarter + different task second-to-last quarter, OR
# 2. Different contractor second-to-last quarter i.e., contractor is new entrant
num_proj_same_task_df[,num_projects_same_task_lag_2:=ifelse(recipient_duns==
                                                                 lag(recipient_duns,2)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code,2),
                                                            lag(num_projects_same_task,2),
                                                            0)]

num_proj_same_task_df[,num_projects_lag_2:=ifelse(recipient_duns==
                                                                 lag(recipient_duns,2)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code,2),
                                                            lag(num_projects,2),
                                                            0)]

###########################################
# LAG OF 3
##########################################
num_proj_same_task_df[,num_projects_same_task_lag_3:=ifelse(recipient_duns==
                                                                 lag(recipient_duns,3)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code,3),
                                                            lag(num_projects_same_task,3),
                                                            0)]


num_proj_same_task_df[,num_projects_lag_3:=ifelse(recipient_duns==
                                                                 lag(recipient_duns,3)&
                                                            product_or_service_code==
                                                              lag(product_or_service_code,3),
                                                            lag(num_projects,3),
                                                            0)]

###########################################
# ADD IT UP
##########################################

num_proj_same_task_df[,num_projs_same_task_past_three_qtrs:=num_projects_same_task_lag_2+
                                                          num_projects_same_task_lag_1+
                                                          num_projects_same_task_lag_3]


num_proj_same_task_df[,num_projs_past_three_qtrs:=num_projects_lag_1+
                                                  num_projects_lag_2+
                                                  num_projects_lag_3]

reg_df_subset=merge(num_proj_same_task_df,
                    reg_df_subset,
                    by=c('recipient_duns',
                         'product_or_service_code',
                         'action_date_year_quarter'),
                    all.y=T)

# more experience --> num_proj_same_task/num_proj increases
# contractor_inexperience decreases

# less experience --> num_proj_same_task/num_proj decreases
# contractor_inexperience increases

reg_df_subset[,contractor_inexperience:=ifelse(num_projs_past_three_qtrs>0,
                                               (1-num_projs_same_task_past_three_qtrs/num_projs_past_three_qtrs),
                                               1)]

# If num_projs_past_three_qtrs==0 => num_projs_same_task_past_three_qtrs==0
# Inexperience = 1 because contractor is "new entrant"
```

* Let $n^{task}_{i,k,t}=$ Number of projects of same task as project $i$ held by contractor $k$ in past three quarters
* Let $n_{i,k,t}=$ Number of projects held by the contractor $k$ of project $i$ in past three quarters
* For contractor $k$, define:
    * Inexperience$_{ikt}= 1 - \frac{n^{task}_{i,k,t}}{n_{i,k,t}}$ if $n_{i,k,t}>0$
    * Inexperience$_{ikt}= 1$ if $n_{i,k,t}=0$.

```{r histogram, echo=FALSE, results='asis'}
hist(reg_df_subset$contractor_inexperience,
     main="Inexperience",
     xlab="",
     ylab="")
```

```{r inexp, include=FALSE}
m1=feols(contractor_inexperience~treat_new+
                                  treat_new:post_t+
                                  post_t,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))


m2=feols(contractor_inexperience~treat_new+
                                  treat_new:post_t+
                                 log(wins_project_quarter_stage)+
                                 post_t,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))


m3=feols(contractor_inexperience~treat_new+
                                  treat_new:post_t+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))


m4=feols(contractor_inexperience~treat_new+
                                  treat_new:post_t+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter+
                                  product_or_service_code,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

m5=feols(contractor_inexperience~treat_new+
                                  treat_new:post_t+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter+
                                  product_or_service_code+
                                  naics_code,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))


contractor_experience=list(m2,m3,m4,m5)
```

```{r no_experience, include=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                                  contractor_inexperience+
                                  treat_new:contractor_inexperience+
                                  post_t:contractor_inexperience+
                                  treat_new:post_t+
                                  treat_new:post_t:contractor_inexperience+
                                  post_t,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

m2=feols(wins_percentage_delay~treat_new+
                                  contractor_inexperience+
                                  treat_new:contractor_inexperience+
                                  post_t:contractor_inexperience+
                                  treat_new:post_t+
                                  treat_new:post_t:contractor_inexperience+
                                 log(wins_project_quarter_stage)+
                                  post_t,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

m3=feols(wins_percentage_delay~treat_new+
                                  contractor_inexperience+
                                  treat_new:contractor_inexperience+
                                  post_t:contractor_inexperience+
                                  treat_new:post_t+
                                  treat_new:post_t:contractor_inexperience+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

m4=feols(wins_percentage_delay~treat_new+
                                  contractor_inexperience+
                                  treat_new:contractor_inexperience+
                                  post_t:contractor_inexperience+
                                  treat_new:post_t+
                                  treat_new:post_t:contractor_inexperience+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter+
                                  product_or_service_code,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

m5=feols(wins_percentage_delay~treat_new+
                                  contractor_inexperience+
                                  treat_new:contractor_inexperience+
                                  post_t:contractor_inexperience+
                                  treat_new:post_t+
                                  treat_new:post_t:contractor_inexperience+
                                 log(wins_project_quarter_stage)|
                                 action_date_year_quarter+
                                  product_or_service_code+
                                  naics_code,
                                  cluster=~contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1))

contractor_experience_delays=list(m2,m3,m4,m5)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(c("wins_percentage_delay"="Percentage delay rate",
                 "treat_new"="Treat",
                 "post_t"="Post",
                 "log(wins_project_quarter_stage)"="Ln(Stage)",
                 "contractor_inexperience"="Inexperience",
                 "action_date_year_quarter"="Time",
                 "product_or_service_code"="Task",
                 "naics_code"="Industry",
                 "contract_award_unique_key"="Project ID"))

etable(contractor_experience,
       tex=T,
       style.tex = style.tex(depvar.title = "",
                             model.title = "",
                             model.format = "I",
                             var.title = "",
                             line.bottom = "simple",
                             line.top = "simple",
                             stats.title = "",
                             fixef.title = "",
                             fixef.suffix = " FE",
                             yesNo = c("Yes","No")),
       digits='r2',
       digits.stats = 'r2',
       fontsize = "small")

etable(contractor_experience_delays,
       tex=T,
       style.tex = style.tex(depvar.title = "",
                             model.title = "",
                             model.format = "I",
                             var.title = "",
                             line.bottom = "simple",
                             line.top = "simple",
                             stats.title = "",
                             fixef.title = "",
                             fixef.suffix = " FE",
                             yesNo = c("Yes","No")),
       digits='r2',
       digits.stats = 'r2',
       fontsize = "small")
```
