---
title: "NETS data"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(xtable)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r read_nets, include=FALSE}
df=fread('/Users/vibhutid_admin/Downloads/NETSData_Public2020.txt')
```

```{r merge, include=FALSE}
df_sub=df[,c("DunsNumber",
             "Sales10","Sales11","Sales12","Sales13",
              "Emp10","Emp11","Emp12","Emp13",
              "PayDexMin10","PayDexMax10",
              "PayDexMin11","PayDexMax11",
              "PayDexMin12","PayDexMax12",
              "PayDexMin13","PayDexMax13",
              "DnBRating10","DnBRating11","DnBRating12","DnBRating13")]


df_sub[,average_paydex:= rowMeans(.SD,na.rm=T), .SDcols = c('PayDexMin10',
                                              'PayDexMin11',
                                              'PayDexMin12',
                                              'PayDexMin13')]

df_sub[,average_sales:= rowMeans(.SD,na.rm=T), .SDcols = c("Sales10", 
                                              "Sales11",
                                              "Sales12",
                                              "Sales13")]

df_sub[,average_employees:= rowMeans(.SD,na.rm=T), .SDcols = c("Emp10", 
                                                  "Emp11",
                                                  "Emp12",
                                                  "Emp13")]

reg_df_subset=merge(reg_df_subset,
        df_sub[,c('DunsNumber',
                  'average_sales',
                  'average_paydex',
                  'average_employees')],
        by.x='recipient_duns',
        by.y='DunsNumber',
        all.x=T)
```


```{r get_summary, include=FALSE}
small_empty_paydex=nrow(reg_df_subset[treat_new==1 &
                                 is.na(average_paydex)])/nrow(reg_df_subset[treat_new==1])

large_empty_paydex=nrow(reg_df_subset[treat_new==0 &
                                 is.na(average_paydex)])/nrow(reg_df_subset[treat_new==0])


small_empty_sales=nrow(reg_df_subset[treat_new==1 &
                                 is.na(average_sales)])/nrow(reg_df_subset[treat_new==1])

large_empty_sales=nrow(reg_df_subset[treat_new==0 &
                                 is.na(average_sales)])/nrow(reg_df_subset[treat_new==0])


small_empty_emp=nrow(reg_df_subset[treat_new==1 &
                                 is.na(average_employees)])/nrow(reg_df_subset[treat_new==1])

large_empty_emp=nrow(reg_df_subset[treat_new==0 &
                                 is.na(average_employees)])/nrow(reg_df_subset[treat_new==0])

summary_stat=data.table()

summary_stat[,Metric:=rep('% of empty obs.',2)]
summary_stat[,`Business Type`:=c("Small","Large")]
summary_stat[,`Sales`:=c(small_empty_sales,large_empty_sales)]
summary_stat[,`PayDex`:=c(small_empty_paydex,large_empty_paydex)]
summary_stat[,`Employees`:=c(small_empty_emp,large_empty_emp)]
```

```{r output, echo=FALSE, results='asis'}
print(xtable(as.data.frame(summary_stat),digits=2),include.rowlabels=F)
```
