---
title: "Congestion -- Restrict to competitively awarded projects"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array,makecell}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(DescTools) 
library(ggplot2)
```

```{r read_file_path, include=FALSE}
source(paste0(dirname(getwd()),
              "/file_paths.R"), 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df=fread(paste0(input_path,
                 'quickpay_delays.csv'))
```

* $Treat_i=1$ for contractors that hold at least one small project over the sample horizon.
* $Treat_i=0$ for contractors that hold only large projects.
* For treated group, focus only on new projects/budget/etc. acquired for small projects.
* For the control group, by construction, changes will account for new projects/tasks/budget acquired for large projects

```{r small_vs_large_contractors,include=FALSE}
small_contractors=unique(reg_df[treat_i==1]$recipient_duns)
large_contractors=unique(reg_df[treat_i==0]$recipient_duns)

only_large_contractors=setdiff(large_contractors,
                               small_contractors)

only_small_contractors=setdiff(small_contractors,
                               large_contractors)

```

```{r define_treat,include=FALSE}
reg_df_sub=reg_df[competitively_awarded_i==1]

reg_df_sub[,two_digit_task_code:=
             substr(product_or_service_code,1,2)]

contractor_quarter_all=reg_df_sub[,.(list_two_digit_task_codes_all=list(unique(
                                        two_digit_task_code)),
                                  num_projects_all=
                                        n_distinct(
                                          contract_award_unique_key),
                                 num_tasks_two_digit_all=
                                   n_distinct(two_digit_task_code),
                                 total_budget_in_millions_all=
                                   sum(winsorized_initial_budget_i,
                                       na.rm=T)/1000000),
                                   by=c('recipient_duns',
                                        'action_date_year_quarter')]

contractor_quarter_small=reg_df_sub[business_type=="S",
                                    .(list_two_digit_task_codes_small=
                                         list(unique(
                                        two_digit_task_code)),
                                  num_projects_small=
                                        n_distinct(
                                          contract_award_unique_key),
                                 num_tasks_two_digit_small=
                                   n_distinct(two_digit_task_code),
                                 total_budget_in_millions_small=
                                   sum(winsorized_initial_budget_i,
                                       na.rm=T)/1000000),
                                   by=c('recipient_duns',
                                        'action_date_year_quarter')]

contractor_quarter=merge(contractor_quarter_all,
                         contractor_quarter_small,
                         by=c('recipient_duns',
                                        'action_date_year_quarter'),
                         all.x=T)
```

```{r}
contractor_quarter[,post_t:=ifelse(action_date_year_quarter>
                                     as.Date('2011-04-27'),1,0)]

contractor_quarter[,treat_i:=case_when(recipient_duns%in%
                                         small_contractors~1,
                                       recipient_duns%in%
                                         only_large_contractors~0)]

contractor_quarter=contractor_quarter[!is.na(recipient_duns)]
contractor_quarter=contractor_quarter[order(
                                        recipient_duns,                                          action_date_year_quarter)]
```

```{r}
# If small project, use only changes in small projects
# Else use all
contractor_quarter[,list_two_digit_task_codes:=ifelse(
                                    treat_i==1,
                                    list_two_digit_task_codes_small,       
                                    list_two_digit_task_codes_all)]

# contractor_quarter[,num_projects:=ifelse(
#                                     treat_i==1,
#                                     num_projects_small,       
#                                     num_projects_all)]
# 
# 
# contractor_quarter[,num_tasks_two_digit:=ifelse(
#                                     treat_i==1,
#                                     num_tasks_two_digit_small,       
#                                     num_tasks_two_digit_all)]
# 
# contractor_quarter[,total_budget_in_millions:=ifelse(
#                                     treat_i==1,
#                                     total_budget_in_millions_small,       
#                                     total_budget_in_millions_all)]
```

```{r}
# Jaccard similarity per quarter (Intersection/Union)
# contractor_quarter[, similarity_score_two_digit := ifelse(
#     recipient_duns == lag(recipient_duns),
#     lengths(Map(intersect, list_two_digit_task_codes, lag(list_two_digit_task_codes))) /
#     lengths(Map(union, list_two_digit_task_codes, lag(list_two_digit_task_codes))),
#     NaN
# )]
# 
# contractor_quarter[, dissimilarity_score_two_digit := 1-similarity_score_two_digit]

contractor_quarter[, task_extension_score_two_digit := ifelse(
    recipient_duns == lag(recipient_duns),
    lengths(Map(setdiff, 
                list_two_digit_task_codes, 
                lag(list_two_digit_task_codes))) /
    lengths(list_two_digit_task_codes),
    NaN
)]
```

```{r similarity_score_two_digit, include=FALSE}
m1=feols(task_extension_score_two_digit~treat_i+
          post_t:treat_i+post_t,
         cluster=~recipient_duns, 
        data=contractor_quarter)

m2=feols(task_extension_score_two_digit~treat_i+
          post_t:treat_i|
          action_date_year_quarter,
          cluster=~recipient_duns, 
        data=contractor_quarter)

m3=feols(task_extension_score_two_digit~post_t:treat_i|recipient_duns+
          action_date_year_quarter,
          cluster=~recipient_duns, 
        data=contractor_quarter)

task_extension_score_regs_0=list(m1,m2)
task_extension_score_regs=list(m1,m2,m3)
```

```{r read_data_delays,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))

reg_df_subset=merge(reg_df_subset,
                    contractor_quarter[,c('recipient_duns',
                                          'action_date_year_quarter',
                                          'task_extension_score_two_digit')],
                    by=c('recipient_duns',
                                          'action_date_year_quarter'),
                    all.x=T)
```

```{r similarity_interaction,include=FALSE}
m1=feols(wins_percentage_delay~+
            task_extension_score_two_digit+
                            post_t:treat_new+
        treat_new:post_t:task_extension_score_two_digit+
        post_t:task_extension_score_two_digit+
          treat_new:task_extension_score_two_digit+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[competitively_awarded_i==1])

m2=feols(wins_percentage_delay~+
            task_extension_score_two_digit+
                            post_t:treat_new+
        treat_new:post_t:task_extension_score_two_digit+
        post_t:task_extension_score_two_digit+
          treat_new:task_extension_score_two_digit+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[competitively_awarded_i==1])

m3=feols(wins_percentage_delay~+
            task_extension_score_two_digit+
                            post_t:treat_new+
        treat_new:post_t:task_extension_score_two_digit+
        post_t:task_extension_score_two_digit+
          treat_new:task_extension_score_two_digit+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[competitively_awarded_i==1])

m4=feols(wins_percentage_delay~+
            task_extension_score_two_digit+
                            post_t:treat_new+
        treat_new:post_t:task_extension_score_two_digit+
        post_t:task_extension_score_two_digit+
          treat_new:task_extension_score_two_digit+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            recipient_duns+naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[competitively_awarded_i==1])

task_extension_score_interaction=list(m2,m3,m4)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("num_tasks_two_digit"="$NumTasks_{kt}$",
                      "wins_percentage_delay"="$PercentDelayRate_{it}$",
                      'similarity_score_two_digit'="$TaskPermanence_{kt}$",
                      'task_extension_score_two_digit'="$TaskExtension_{kt}$",
                      "total_budget_in_millions"= 
                        "$TotalBudget_{kt}$ (millions)",
                      'recipient_duns'="Contractor",
                      "num_projects"="$NumProjects_{kt}$",
                      "post_t"="$Post_t$",
                      "treat_i"="$Treat_k$",
                      "treat_new"="$Treat_i$",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))

etable(task_extension_score_regs,
       digits='r2',
       digits.stats = 2,
       fontsize = "tiny",
       caption="Congestion and the QuickPay reform",
       fitstat = c("n","r2"),
       style.tex=style.tex(fixef.title = "\\midrule",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Sample restricted to competitively awarded projects. Treat is an indicator that equals one for contractors that hold at least one small project during the observation horizon. Control group constitutes contractors who hold only large projects during the observation horizon.",
       tex=TRUE)

etable(task_extension_score_interaction,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       caption="Task score and the QuickPay reform",
       fitstat = c("n","r2"),
       style.tex=style.tex(fixef.title = "\\midrule",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Sample restricted to competitively awarded projects. Treat is an indicator that equals one for small projects. Control group constitutes projects belonging to contractors who hold only large projects during the observation horizon.",
       tex=TRUE)
```

```{r plots, echo=FALSE, message=FALSE,warning=FALSE, results='asis'}
contractor_quarter[,relative_quarter:=case_when(action_date_year_quarter=="2010-03-31"~-5,
                                                    action_date_year_quarter=="2010-06-30"~-4,
                  action_date_year_quarter=="2010-09-30"~-3,
                  action_date_year_quarter=="2010-12-31"~-2,
                  action_date_year_quarter=="2011-03-31"~-1,
                  action_date_year_quarter=="2011-06-30"~0,
                  action_date_year_quarter=="2011-09-30"~1,
                  action_date_year_quarter=="2011-12-31"~2,
                  action_date_year_quarter=="2012-03-31"~3,
                  action_date_year_quarter=="2012-06-30"~4)]

es=feols(task_extension_score_two_digit ~ i(relative_quarter, treat_i, ref = -1) +treat_i|
		     action_date_year_quarter,     
		 cluster = ~recipient_duns,
		 data = contractor_quarter)

df_summary=contractor_quarter[,.(mean_dissimilarity=mean(task_extension_score_two_digit,
                                                      na.rm=T)),
                              by=c('treat_i','action_date_year_quarter')]
# Plot trends
mean_plot=ggplot(df_summary[!is.na(mean_dissimilarity)], aes(
  x = as.factor(action_date_year_quarter),
  y = mean_dissimilarity,
  group = as.factor(treat_i)
)) +
  # Lines
  geom_line(aes(linetype = as.factor(treat_i)),
            color = "black", linewidth = 0.6) +
  # Points
  geom_point(aes(shape = as.factor(treat_i)),
             color = "black", size = 2.5) +
  # Custom style for 0/1
  scale_linetype_manual(values = c("0" = "dotted", "1" = "solid")) +
  scale_shape_manual(values = c("0" = 16, "1" = 17)) +
  # Labels and theme
  labs(
    x = "Year-Quarter",
    y = "Mean Dis-similarity Score",
    linetype = "Treatment",
    shape = "Treatment",
    title = "Dis-similarity Trends by Treatment Group"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)  # slant labels
  )

iplot(es)

mean_plot
```
