---
title: "Percentage Delay Rate (Two Quarters): QuickPay (2009-2012)"
date: " `r format(Sys.time(), '%b %d, %Y')`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(openxlsx)
library(tidyverse)
library(dplyr)
library(pryr)
library(lfe) # linear fixed effects 
library(DescTools) 
library(zoo) # for year quarter
library(stargazer)
library(broom)
library(data.table)
library(scales)
```

```{r set_path_for_exporting, include=FALSE}
#tables_folder='~/Desktop/git_folders/QuickPay/QP_paper/Tables/percentage_delay_rate'
#figures_folder='~/Desktop/git_folders/QuickPay/QP_paper/Figures'
data_folder='~/Dropbox/data_quickpay/qp_data/'
```

```{r read_data, include=FALSE}
# Keep only projects whose start dates match with API one
projects_to_keep=fread(paste0(data_folder,'projects_to_keep.csv'))

# read quarterly resampled data
df=fread(paste0(data_folder,'resampled_qp_data/qp_resampled_data_fy10_to_fy12_with_zero_obs.csv'))
# specify date columns
date_cols=c("action_date_year_quarter","last_reported_start_date","last_reported_end_date")
df[,(date_cols):= lapply(.SD, as.Date), .SDcols = date_cols]

# restrict to quarter ending June 30, 2012
df=subset(df,as.Date(action_date_year_quarter)<max(as.Date('2012-07-01'))&
             contract_award_unique_key%in%projects_to_keep$contract_award_unique_key)
# data is truncated at July 1, 2012 -- 
# so quarter ending Sept 30, 2012 will only have values as of July 1, 2012

df_first_reported=fread(paste0(data_folder,'qp_data_first_reported.csv'))
# contains time-invariant contract characteristics -- info when contract first appeared in the data

```

```{r assign_variables_1, include=FALSE}
# Assign variables: Delay, Winsorized Delay, Post_t, Treat_i

# sort by contract id and date 
df=df[order(contract_award_unique_key,
            action_date_year_quarter)]

# determine delay over each quarter
df[,delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_end_date-lag(last_reported_end_date,1),NaN)]

# winsorize quarter-to-quarter delay
df[,winsorized_delay:=Winsorize(delay,na.rm=TRUE)]

#Post_t: A dummy that period t is post-treatment
df[,post_t:=ifelse(action_date_year_quarter>as.Date("2011-04-27"),1,0)]
# quickpay implemented on 27 April 2011. So all quarters starting 30 June 2011 will be in post-period

#Treat_i: A dummy that contract i is in the treatment group
df[,treat_i:=ifelse(business_type=="S",1,0)]
# quickpay was implemented for small business contracts

# Project age is a highly skewed variable
# assign number of quarters since project started: "project age" in some sense
df[, project_quarter_age := rowid(contract_award_unique_key)]
df[,project_quarter_tercile:=as.factor(ntile(project_quarter_age,3))]
# Including it as fixed effects doesn't work because projects in treatment and control are not always in same "tercile" while controling for everything else. 
```

```{r delay_over_two_quarters, include=FALSE}
keep_dates=as.Date(c('2010-03-31',
             '2010-09-30',
             '2011-03-31',
             '2011-09-30', 
             '2012-03-31'))

df=df[order(contract_award_unique_key,
            action_date_year_quarter)]

df[,two_quarter_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1)&
                                action_date_year_quarter%in%keep_dates,
                              delay+lag(delay,1),NaN)]

df[,two_quarter_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1)&
                                action_date_year_quarter%in%keep_dates &
                                is.na(lag(delay,1)),
                              delay,two_quarter_delay)]
```

```{r assign_variables_2, include=FALSE}

# ContractFinancing_i

df_first_reported[,contract_financing_i:=ifelse(!is.null(contract_financing_code)&
                                       !contract_financing_code%in%c("Z", ""),1,0)]

# Competition_i
df_first_reported[,competitively_awarded_i:=ifelse(!is.null(extent_competed_code)&
                                          !extent_competed_code%in%c("","G","B", "C","E"),1,0)]

# InitialDuration_i

df_first_reported[,initial_duration_in_days_i:=
                    as.numeric(
                    as.Date(period_of_performance_current_end_date)-
                    as.Date(period_of_performance_start_date))]

df_first_reported[,winsorized_initial_duration_in_days_i:=
                    Winsorize(as.numeric(
                    as.Date(period_of_performance_current_end_date)-
                    as.Date(period_of_performance_start_date)),na.rm=T)]

# InitialBudget_i

df_first_reported[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,na.rm=T)]

# Change type to string modification number
df_first_reported[,modification_number:=as.character(modification_number)]

select_cols=c("contract_award_unique_key",
              "recipient_duns",
              "naics_code",
              "product_or_service_code",
              "modification_number",
              "number_of_offers_received",
              "contract_financing_i",
              "competitively_awarded_i",
              "period_of_performance_start_date",
              "initial_duration_in_days_i",
              "winsorized_initial_duration_in_days_i",
              "winsorized_initial_budget_i")

# not necessary but speed efficient to set keys
setkey(df_first_reported[,..select_cols],
       contract_award_unique_key)
setkey(df,contract_award_unique_key)
```

```{r combine_dfs, include=FALSE}
# Combine all variables into dataframe needed for regression 
reg_df=merge(df,
             df_first_reported[,..select_cols],
             all.x = TRUE, # keep values in df, add columns of df_first_reported_cols
             by=c("contract_award_unique_key"))

# sort by contract id and date (just to be doubly sure)
reg_df=reg_df[order(contract_award_unique_key,
            action_date_year_quarter)]

reg_df[,winsorized_two_quarter_delay:=Winsorize(two_quarter_delay,na.rm=T)]
```


# Delays over time

* Sample restricted to projects for which start dates matches the one in API
   * This is done by using first reported "action_date" and "date_signed" 

```{r plot_pc_delay, echo=FALSE, results='asis'}
mean_delay=reg_df[!is.na(winsorized_two_quarter_delay), 
              mean(winsorized_two_quarter_delay),  
              by = c('action_date_year_quarter','business_type')]
mean_delay[,year_quarter:=format(action_date_year_quarter,"%Y-%b")]
mean_delay=mean_delay[order(action_date_year_quarter,business_type)]

ggplot(mean_delay, aes(x=year_quarter,
               y=V1, 
               group = business_type, 
               shape=business_type, 
               linetype=business_type))+
    geom_line() +    
    scale_x_discrete(limits=mean_delay$year_quarter)+
    geom_point(size=3)+
    labs(x="Year-Quarter", y = "Average delay rate per two-quarter")+  
    annotate("text", label = "QuickPay\n implemented", x = 3, y = 30,color="dimgrey")+
    geom_vline(xintercept = 4.2, linetype="solid", 
                color = "gray", size=1.5)+
    scale_shape_discrete(name  ="Business Size",
                          breaks=c("O", "S"),
                          labels=c("Large", "Small"))+
    scale_linetype_discrete(name="Business Size",
                          breaks=c("O", "S"),
                          labels=c("Large", "Small"))+
    theme(axis.text.x = element_text(angle = 90),
    axis.line = element_line(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    legend.text = element_text(size=12))
```

## Normalized delay rate

```{r normalized_plot,echo=FALSE, results='asis'}

large_baseline=subset(mean_delay,year_quarter=='2010-Jun' & business_type=="O")$V1
small_baseline=subset(mean_delay,year_quarter=='2010-Jun' & business_type=="S")$V1
mean_delay[,V2:=ifelse(business_type=="S",V1*100/small_baseline,V1*100/large_baseline)]

ggplot(mean_delay, aes(x=year_quarter,
               y=V2, 
               group = business_type, 
               shape=business_type, 
               linetype=business_type))+
    geom_line() +    
    scale_x_discrete(limits=mean_delay$year_quarter)+
    geom_point(size=3)+
    labs(x="Year-Quarter", y = "Average delay rate per two quarters \n (normalized by delay in 2010-Jun) ")+  
    annotate("text", label = "QuickPay\n implemented", x = 4, y = 160,color="dimgrey")+
    geom_vline(xintercept = 4.2, linetype="solid", 
                color = "gray", size=1.5)+
    scale_shape_discrete(name  ="Business Size",
                          breaks=c("O", "S"),
                          labels=c("Large", "Small"))+
    scale_linetype_discrete(name="Business Size",
                          breaks=c("O", "S"),
                          labels=c("Large", "Small"))+
    theme(axis.text.x = element_text(angle = 90),
    axis.line = element_line(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    legend.text = element_text(size=12))

# ggsave(path=figures_folder,
#        width = 8,
#        height = 5,
#        filename = "pc_delay_normalized.png")

```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

# Full Sample Regressions

$$ PercentDelay_{it} = \beta_0 + \beta_1 Treat_i + \beta_2 Post_t + \beta_3 (Treat_i \times Post_t) + e_{it}$$ 

$$ \begin{aligned} PercentDelay_{it} &=& \alpha+\beta_0 Treat_i + \beta_1 Post_t + \beta_2 (Treat_i \times Post_t)\\
&+&  X_i + (Post_t \times X_i) + \mu_t + \theta_{firm} + \lambda_{task}+ \epsilon_{it}
\end{aligned}$$


## One Quarter

```{r baseline_regressions, echo=FALSE, results='asis'}
# Baseline Regressions 
baseline_reg=felm(winsorized_delay~treat_i+
                     post_t:treat_i+
                     post_t|
                    0| # no fixed effects
                    0| # no IV
                    contract_award_unique_key, # clustered at project level
                  data=reg_df, 
                  exactDOF = TRUE, 
                  cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_no_fe=felm(winsorized_delay~treat_i+
                           post_t:treat_i+
                           post_t+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            0|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_time_fe=felm(winsorized_delay~treat_i+
                             post_t:treat_i+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_time_task_fe=felm(winsorized_delay~treat_i+
                              post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_all_fe=felm(winsorized_delay~treat_i+
                            post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            recipient_duns+product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
base_table<-stargazer(baseline_reg,
          controls_and_no_fe,
          controls_and_time_fe,
          controls_time_task_fe,
          controls_and_all_fe,
          title = "Effect of QuickPay on project delay rates",
          dep.var.labels="$PercentDelay_{it}$",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$","$Post_t$","$Treat_i \\times Post_t$","Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          digits=2,
          digits.extra=2,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Duration, Budget, Bids","No",rep("Yes",4)),
                           c("$Post_t \\times$  (Duration, Budget, Bids)","No",rep("Yes",4)),
                        #   c("Project age","No",rep("Yes",4)),
                           c("Year-Quarter fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Contractor fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'number_of_offers_received',
                   'post_t:winsorized_initial_duration_in_days_i',
                   'post_t:winsorized_initial_budget_i',
                   'post_t:number_of_offers_received'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level."),
          header=F)

# base_table_tex=make_tex_pieces(base_table)
# # Write to file
# write(base_table_tex,
#       paste0(tables_folder,"/base_table.tex"))

```

## Two-Quarters

```{r two_quarters, echo=FALSE, results='asis'}
# Baseline Regressions 
baseline_reg=felm(winsorized_two_quarter_delay~treat_i+
                     post_t:treat_i+
                     post_t|
                    0| # no fixed effects
                    0| # no IV
                    contract_award_unique_key, # clustered at project level
                  data=reg_df, 
                  exactDOF = TRUE, 
                  cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_no_fe=felm(winsorized_two_quarter_delay~treat_i+
                           post_t:treat_i+
                           post_t+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            0|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_time_fe=felm(winsorized_two_quarter_delay~treat_i+
                             post_t:treat_i+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_time_task_fe=felm(winsorized_two_quarter_delay~treat_i+
                              post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_all_fe=felm(winsorized_two_quarter_delay~treat_i+
                            post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            recipient_duns+product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=reg_df, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
base_table<-stargazer(baseline_reg,
          controls_and_no_fe,
          controls_and_time_fe,
          controls_time_task_fe,
          controls_and_all_fe,
          title = "Effect of QuickPay on project delay rates",
          dep.var.labels="$PercentDelay_{it}$",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$","$Post_t$","$Treat_i \\times Post_t$","Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          digits=2,
          digits.extra=2,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Duration, Budget, Bids","No",rep("Yes",4)),
                           c("$Post_t \\times$  (Duration, Budget, Bids)","No",rep("Yes",4)),
                        #   c("Project age","No",rep("Yes",4)),
                           c("Year-Quarter fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Contractor fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'number_of_offers_received',
                   'post_t:winsorized_initial_duration_in_days_i',
                   'post_t:winsorized_initial_budget_i',
                   'post_t:number_of_offers_received'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level."),
          header=F)

# base_table_tex=make_tex_pieces(base_table)
# # Write to file
# write(base_table_tex,
#       paste0(tables_folder,"/base_table.tex"))

```

# Truncated Sample with Positive Delays

$$ PercentDelay_{it} = \beta_0 + \beta_1 Treat_i + \beta_2 Post_t + \beta_3 (Treat_i \times Post_t) + e_{it}$$ 

$$ \begin{aligned} PercentDelay_{it} &=& \alpha+\beta_0 Treat_i + \beta_1 Post_t + \beta_2 (Treat_i \times Post_t)\\
&+&  X_i + (Post_t \times X_i) + \mu_t + \theta_{firm} + \lambda_{task}+ \epsilon_{it}
\end{aligned}$$

## One Quarter

```{r baseline_reg_truncated, echo=FALSE, results='asis'}
# Baseline Regressions 
baseline_reg=felm(winsorized_delay~treat_i+
                     post_t:treat_i+
                     post_t|
                    0| # no fixed effects
                    0| # no IV
                    contract_award_unique_key, # clustered at project level
                  data=subset(reg_df, winsorized_delay!=0),
                  exactDOF = TRUE, 
                  cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_no_fe=felm(winsorized_delay~treat_i+
                           post_t:treat_i+
                           post_t+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            0|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_time_fe=felm(winsorized_delay~treat_i+
                             post_t:treat_i+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_time_task_fe=felm(winsorized_delay~treat_i+
                              post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_all_fe=felm(winsorized_delay~treat_i+
                            post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            recipient_duns+product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
base_table<-stargazer(baseline_reg,
          controls_and_no_fe,
          controls_and_time_fe,
          controls_time_task_fe,
          controls_and_all_fe,
          title = "Effect of QuickPay on project delay rates",
          dep.var.labels="$PercentDelay_{it}$",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$","$Post_t$","$Treat_i \\times Post_t$","Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          digits=2,
          digits.extra=2,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Duration, Budget, Bids","No",rep("Yes",4)),
                           c("$Post_t \\times$  (Duration, Budget, Bids)","No",rep("Yes",4)),
                        #   c("Project age","No",rep("Yes",4)),
                           c("Year-Quarter fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Contractor fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'number_of_offers_received',
                   'post_t:winsorized_initial_duration_in_days_i',
                   'post_t:winsorized_initial_budget_i',
                   'post_t:number_of_offers_received'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level."),
          header=F)

# base_table_tex=make_tex_pieces(base_table)
# # Write to file
# write(base_table_tex,
#       paste0(tables_folder,"/base_table.tex"))

```

## Two Quarters

```{r two_quarters_truncated, echo=FALSE, results='asis'}
# Baseline Regressions 
baseline_reg=felm(winsorized_two_quarter_delay~treat_i+
                     post_t:treat_i+
                     post_t|
                    0| # no fixed effects
                    0| # no IV
                    contract_award_unique_key, # clustered at project level
                  data=subset(reg_df, winsorized_two_quarter_delay!=0),
                  exactDOF = TRUE, 
                  cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_no_fe=felm(winsorized_two_quarter_delay~treat_i+
                           post_t:treat_i+
                           post_t+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            0|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_two_quarter_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
# time fixed effects also included in the following specs
controls_and_time_fe=felm(winsorized_two_quarter_delay~treat_i+
                             post_t:treat_i+
                       #    project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_two_quarter_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_time_task_fe=felm(winsorized_two_quarter_delay~treat_i+
                              post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_two_quarter_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_all_fe=felm(winsorized_two_quarter_delay~treat_i+
                            post_t:treat_i+
                        #   project_quarter_tercile+
                            winsorized_initial_duration_in_days_i+
                            winsorized_initial_budget_i+
                            number_of_offers_received+
                            post_t:winsorized_initial_duration_in_days_i+
                            post_t:winsorized_initial_budget_i+
                            post_t:number_of_offers_received|
                            recipient_duns+product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df, winsorized_two_quarter_delay!=0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
base_table<-stargazer(baseline_reg,
          controls_and_no_fe,
          controls_and_time_fe,
          controls_time_task_fe,
          controls_and_all_fe,
          title = "Effect of QuickPay on project delay rates",
          dep.var.labels="$PercentDelay_{it}$",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$","$Post_t$","$Treat_i \\times Post_t$","Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          digits=2,
          digits.extra=2,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Duration, Budget, Bids","No",rep("Yes",4)),
                           c("$Post_t \\times$  (Duration, Budget, Bids)","No",rep("Yes",4)),
                        #   c("Project age","No",rep("Yes",4)),
                           c("Year-Quarter fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Contractor fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'number_of_offers_received',
                   'post_t:winsorized_initial_duration_in_days_i',
                   'post_t:winsorized_initial_budget_i',
                   'post_t:number_of_offers_received'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level."),
          header=F)

# base_table_tex=make_tex_pieces(base_table)
# # Write to file
# write(base_table_tex,
#       paste0(tables_folder,"/base_table.tex"))

```
