---
title: "Logistic regression: Positive Delay Rate -- QuickPay (2009-2012)"
date: " `r format(Sys.time(), '%b %d, %Y')`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(openxlsx)
library(tidyverse)
library(dplyr)
library(pryr)
library(lfe) # linear fixed effects 
library(DescTools) 
library(zoo) # for year quarter
library(texreg)
library(broom)
library(data.table)
library(scales)
library(fixest)
```

```{r set_path_for_exporting, include=FALSE}
tables_folder='~/Desktop/Research/QuickPay/paper/Tables/logistic_regressions'
figures_folder='~/Desktop/Research/QuickPay/paper/Figures'
data_folder='~/Dropbox/data_quickpay/qp_data/'
```

```{r read_data, include=FALSE}
# Keep only projects whose start dates match with API one
projects_to_keep=fread(paste0(data_folder,'projects_to_keep.csv'))

# read quarterly resampled data
df=fread(paste0(data_folder,'resampled_qp_data/qp_resampled_data_fy10_to_fy12_with_zero_obs.csv'))
# specify date columns
date_cols=c("action_date_year_quarter","last_reported_start_date","last_reported_end_date")
df[,(date_cols):= lapply(.SD, as.Date), .SDcols = date_cols]

# restrict to quarter ending June 30, 2012
df=subset(df,as.Date(action_date_year_quarter)<max(as.Date('2012-07-01'))&
             contract_award_unique_key%in%projects_to_keep$contract_award_unique_key)
# data is truncated at July 1, 2012 -- 
# so quarter ending Sept 30, 2012 will only have values as of July 1, 2012

df_first_reported=fread(paste0(data_folder,'qp_data_first_reported.csv'))
# contains time-invariant contract characteristics -- info when contract first appeared in the data

```

```{r assign_variables_1, include=FALSE}
# Assign variables: Delay, Winsorized Delay, Post_t, Treat_i

# some projects have action dates beyond project end date 
# some could indicate projects that ended in the beginning of a quarter -- so taking 90 days difference
# dropping these -- likely admin/documentation changes

df[,diff_end_date_and_action_date:=as.numeric(last_reported_end_date-action_date_year_quarter)]
# to ensure project ended sometime this quarter
df=subset(df,diff_end_date_and_action_date>-90)


# AD: 2015-06-30; End Date: 2015-03-31

# sort by contract id and date 
df=df[order(contract_award_unique_key,
            action_date_year_quarter)]

# determine quarter-to-quarter delay
df[,delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_end_date-lag(last_reported_end_date,1),NaN)]

# winsorize quarter-to-quarter delay
df[,winsorized_delay:=Winsorize(delay,
                                probs=c(0.05,0.95),
                                na.rm=TRUE)]

#Post_t: A dummy that period t is post-treatment
df[,post_t:=ifelse(action_date_year_quarter>as.Date("2011-04-27"),1,0)]
# quickpay implemented on 27 April 2011. So all quarters starting 30 June 2011 will be in post-period

#Treat_i: A dummy that contract i is in the treatment group
df[,treat_i:=ifelse(business_type=="S",1,0)]
# quickpay was implemented for small business contracts

df[,negative_delay:=ifelse(delay<0,1,0)]

```

```{r assign_variables_2, include=FALSE}

# ContractFinancing_i
df_first_reported[,contract_financing_i:=ifelse(!is.null(contract_financing_code)&
                                       !contract_financing_code%in%c("Z", ""),1,0)]
# Receives financial assistance
df_first_reported[,receives_financial_assistance:=ifelse(receives_grants=="t",1,0)]

# Competition_i
df_first_reported[,competitively_awarded_i:=ifelse(!extent_competed_code%in%c("G","B", "C"),1,0)]

df_first_reported[,initial_end_date:=period_of_performance_current_end_date]
df_first_reported[,initial_start_date:=period_of_performance_start_date]

# InitialDuration_i
df_first_reported[,initial_duration_in_days_i:=
                    as.numeric(
                    as.Date(initial_end_date)-
                    as.Date(initial_start_date))]

select_cols=c("contract_award_unique_key",
              "naics_code",
              "product_or_service_code",
              "number_of_offers_received",
              "contract_financing_i",
              "receives_financial_assistance",
              "competitively_awarded_i",
              "recipient_duns",
              "initial_end_date",
              "initial_start_date",
              "initial_duration_in_days_i",
              "base_and_all_options_value",
              "awarding_sub_agency_code")

# not necessary but speed efficient to set keys
setkey(df_first_reported[,..select_cols],
       contract_award_unique_key)
setkey(df,contract_award_unique_key)
```

```{r combine_dfs, include=FALSE}
# Combine all variables into dataframe needed for regression 
reg_df=merge(df,
             df_first_reported[,..select_cols],
             all.x = TRUE, # keep values in df, add columns of df_first_reported_cols
             by=c("contract_award_unique_key"))

reg_df[,initial_start_date:=as.Date(initial_start_date)]
reg_df[,initial_end_date:=as.Date(initial_end_date)]
reg_df[,action_date_year_quarter:=as.Date(action_date_year_quarter)]

reg_df[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i

reg_df[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

# sort by contract id and date (just to be doubly sure)
reg_df=reg_df[order(contract_award_unique_key,
            action_date_year_quarter)]

# time spent in the project so far/total time of the project
# if project was active in previous quarter
reg_df[,project_quarter_stage:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),as.numeric(lag(action_date_year_quarter,1)-initial_start_date)/as.numeric(lag(last_reported_end_date,1)-initial_start_date),NaN)]

# (action_date_year_quarter-90) to get beginning of the quarter

reg_df[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

# stage at end of quarter -- not using this!
reg_df[,stage_aliter:=as.numeric(action_date_year_quarter-initial_start_date)/as.numeric(last_reported_end_date-initial_start_date)]
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

# Logistic Regressions (Negative Delay)

```{r baseline_regressions, echo=FALSE, results='asis',warning=FALSE}
# Baseline Regressions 

baseline_reg=feglm(negative_delay~treat_i+
                   post_t:treat_i+
                   post_t,
                 data=reg_df,
                 family='binomial',
                 cluster='contract_award_unique_key')

controls_and_no_fe=feglm(negative_delay~treat_i+
                           post_t:treat_i+
                           post_t+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received,
                          data=reg_df,
                          family='binomial',
                         cluster='contract_award_unique_key')

# time fixed effects also included in the following specs
controls_and_time_fe=feglm(negative_delay~treat_i+
                             post_t:treat_i+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_time_task_fe=feglm(negative_delay~treat_i+
                              post_t:treat_i+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_all_fe=feglm(negative_delay~treat_i+
                            post_t:treat_i+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

setFixest_dict(c("treat_i"="$Treat_i$",
                 "post_t"="$Post_t$",
                 "number_of_offers_received"="Number of offers received", 
                 "log(wins_project_quarter_stage)" = "Project stage",
                 "log(1+winsorized_initial_duration_in_days_i)" = "Initial duration",
                 "product_or_service_code"="Task code",
                 "log(1+winsorized_initial_budget_i)"="Initial budget",
                 "naics_code"="NAICS code",
                 "action_date_year_quarter"="Time",
                 "contract_award_unique_key"="Project ID",
                 "negative_delay"="$I(Delay<0)$"))

etable(baseline_reg,
       controls_and_no_fe,
       controls_and_time_fe,
       controls_time_task_fe,
       controls_and_all_fe,
       cluster = "contract_award_unique_key",
       title = "Logit model: Effect of QuickPay",
       digits = "r2",
       tex=TRUE,
       drop=c('Initial budget',
              'Number of offers received',
              'Project stage',
              'Initial duration'),
       digits.stats = 2,
       file=paste0(tables_folder,"/base_positive_logistic.tex"))

# write(base_table_tex,
#       paste0(tables_folder,"/base_positive_logistic.tex"))

```

# Contract Financing

$$ CF_i = \begin{cases} 1, \text{ if project } i \text{ receives contract financing}\\
0, \text{ otherwise} \end{cases}$$

```{r contract_financing, echo=FALSE, results='asis',warning=FALSE}
# Baseline Regressions 
baseline_reg=feglm(negative_delay~treat_i+
                    post_t:treat_i+
                     post_t+
                     treat_i:contract_financing_i+
                    contract_financing_i+
                    post_t:contract_financing_i+
                    post_t:treat_i:contract_financing_i,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_no_fe=feglm(negative_delay~treat_i+
                            post_t+
                            post_t:treat_i+
                           treat_i:contract_financing_i+
                            contract_financing_i+
                            post_t:contract_financing_i+
                            post_t:treat_i:contract_financing_i+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_time_fe=feglm(negative_delay~treat_i+
                            post_t:treat_i+
                           treat_i:contract_financing_i+
                            contract_financing_i+
                            post_t:contract_financing_i+
                            post_t:treat_i:contract_financing_i+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)
# time fixed effects also included in the following specs
controls_time_task_fe=feglm(negative_delay~treat_i+
                            post_t:treat_i+
                           treat_i:contract_financing_i+
                            contract_financing_i+
                            post_t:contract_financing_i+
                            post_t:treat_i:contract_financing_i+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_all_fe=feglm(negative_delay~treat_i+
                            post_t:treat_i+
                           treat_i:contract_financing_i+
                            contract_financing_i+
                            post_t:contract_financing_i+
                            post_t:treat_i:contract_financing_i+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

setFixest_dict(c("treat_i"="$Treat_i$",
                 "post_t"="$Post_t$",
                 "contract_financing_i"="$CF_i$",
                 "number_of_offers_received"="Number of offers received", 
                 "log(wins_project_quarter_stage)" = "Project stage",
                 "log(1+winsorized_initial_duration_in_days_i)" = "Initial duration",
                 "product_or_service_code"="Task code",
                 "log(1+winsorized_initial_budget_i)"="Initial budget",
                 "naics_code"="NAICS code",
                 "action_date_year_quarter"="Time",
                 "contract_award_unique_key"="Project ID",
                 "negative_delay"="$I(Delay<0)$"))

etable(baseline_reg,
       controls_and_no_fe,
       controls_and_time_fe,
       controls_time_task_fe,
       controls_and_all_fe,
       cluster = "contract_award_unique_key",
       title = "Logit model: Effect of QuickPay",
       digits = "r2",
       tex=TRUE,
       drop=c('Initial budget',
              'Number of offers received',
              'Project stage',
              'Initial duration'),
       digits.stats = 2)

```


# Competition

## Impact on delays

Define
$$ SA_i = \begin{cases} 1, \text{ if project was signed after QuickPay}\\
0, \text{ otherwise} \end{cases}$$

$$ SB_i = \begin{cases} 1, \text{ if project was signed before QuickPay}\\
0, \text{ otherwise} \end{cases}$$

### Subsample model

```{r competition_delays_subsample, echo=FALSE, results='asis',warning=FALSE}
new_projects_after_quickpay=unique(subset(df_first_reported,action_date>as.Date('2011-04-27'))$contract_award_unique_key)
reg_df[,project_signed_after_quickpay:=ifelse(contract_award_unique_key%in%new_projects_after_quickpay,1,0)]
reg_df[,project_signed_before_quickpay:=ifelse(!contract_award_unique_key%in%new_projects_after_quickpay,1,0)]
baseline_reg=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                                  post_t,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==1))
                                  

controls_and_no_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                                  post_t+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i),
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==1))

controls_and_time_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==1))

controls_time_task_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                            log(1+winsorized_initial_duration_in_days_i)+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            product_or_service_code+
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==1))

controls_and_all_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                            log(1+winsorized_initial_duration_in_days_i)+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==1))


setFixest_dict(c("treat_i"="$Treat_i$",
                 "post_t"="$Post_t$",
                 "contract_financing_i"="$CF_i$",
                 "project_signed_before_quickpay"="$SB_i$",
                 "project_signed_after_quickpay"="$SA_i$",
                 "number_of_offers_received"="Number of offers received", 
                 "log(wins_project_quarter_stage)" = "Project stage",
                 "log(1+winsorized_initial_duration_in_days_i)" = "Initial duration",
                 "product_or_service_code"="Task code",
                 "log(1+winsorized_initial_budget_i)"="Initial budget",
                 "naics_code"="NAICS code",
                 "action_date_year_quarter"="Time",
                 "contract_award_unique_key"="Project ID",
                 "negative_delay"="$I(Delay<0)$"))

etable(baseline_reg,
       controls_and_no_fe,
       controls_and_time_fe,
       controls_time_task_fe,
       controls_and_all_fe,
       cluster = "contract_award_unique_key",
       title = "Logit model: Effect of QuickPay on Competitive Projects",
       digits = "r2",
       tex=TRUE,
       drop=c('Initial budget',
              'Number of offers received',
              'Project stage',
              'Initial duration'),
       digits.stats = 2)
```

```{r non_competitive_delays_subsample, echo=FALSE, results='asis',warning=FALSE}
baseline_reg=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                                  post_t,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==0))
                                  

controls_and_no_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                                  post_t+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i),
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==0))

controls_and_time_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==0))

controls_time_task_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                            log(1+winsorized_initial_duration_in_days_i)+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            product_or_service_code+
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==0))

controls_and_all_fe=feglm(negative_delay~treat_i+
                                  project_signed_after_quickpay+
                                  treat_i:post_t:project_signed_before_quickpay+
                                  treat_i:post_t:project_signed_after_quickpay+
                            log(1+winsorized_initial_duration_in_days_i)+
                             log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=subset(reg_df,competitively_awarded_i==0))


setFixest_dict(c("treat_i"="$Treat_i$",
                 "post_t"="$Post_t$",
                 "contract_financing_i"="$CF_i$",
                 "project_signed_before_quickpay"="$SB_i$",
                 "project_signed_after_quickpay"="$SA_i$",
                 "number_of_offers_received"="Number of offers received", 
                 "log(wins_project_quarter_stage)" = "Project stage",
                 "log(1+winsorized_initial_duration_in_days_i)" = "Initial duration",
                 "product_or_service_code"="Task code",
                 "log(1+winsorized_initial_budget_i)"="Initial budget",
                 "naics_code"="NAICS code",
                 "action_date_year_quarter"="Time",
                 "contract_award_unique_key"="Project ID",
                 "negative_delay"="$I(Delay<0)$"))

etable(baseline_reg,
       controls_and_no_fe,
       controls_and_time_fe,
       controls_time_task_fe,
       controls_and_all_fe,
       cluster = "contract_award_unique_key",
       title = "Logit model: Effect of QuickPay on Non-Competitive Projects",
       digits = "r2",
       tex=TRUE,
       drop=c('Initial budget',
              'Number of offers received',
              'Project stage',
              'Initial duration'),
       digits.stats = 2)

```

### Four-way interaction

```{r competition_delays_combined, echo= FALSE, results ='asis',warning=FALSE}
baseline_reg=feglm(negative_delay~treat_i+
                                   project_signed_after_quickpay+
                                   competitively_awarded_i+
                     treat_i:competitively_awarded_i+
                     post_t:competitively_awarded_i+
                             log(wins_project_quarter_stage)+
                     project_signed_after_quickpay:competitively_awarded_i+
                     treat_i:post_t+
                     treat_i:post_t:competitively_awarded_i+
                     treat_i:post_t:project_signed_after_quickpay+
                     treat_i:post_t:project_signed_after_quickpay:competitively_awarded_i+
                     post_t,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_no_fe=feglm(negative_delay~treat_i+
                                   project_signed_after_quickpay+
                                   competitively_awarded_i+
                     treat_i:competitively_awarded_i+
                             log(wins_project_quarter_stage)+
                     post_t:competitively_awarded_i+
                     project_signed_after_quickpay:competitively_awarded_i+
                     treat_i:post_t+
                     treat_i:post_t:competitively_awarded_i+
                     treat_i:post_t:project_signed_after_quickpay+
                     treat_i:post_t:project_signed_after_quickpay:competitively_awarded_i+
                     post_t+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i),
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_time_fe=feglm(negative_delay~treat_i+
                                   project_signed_after_quickpay+
                                   competitively_awarded_i+
                             log(wins_project_quarter_stage)+
                     treat_i:competitively_awarded_i+
                     post_t:competitively_awarded_i+
                     project_signed_after_quickpay:competitively_awarded_i+
                     treat_i:post_t+
                     treat_i:post_t:competitively_awarded_i+
                     treat_i:post_t:project_signed_after_quickpay+
                     treat_i:post_t:project_signed_after_quickpay:competitively_awarded_i+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                                   action_date_year_quarter,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_time_task_fe=feglm(negative_delay~treat_i+
                                   project_signed_after_quickpay+
                                   competitively_awarded_i+
                     treat_i:competitively_awarded_i+
                     post_t:competitively_awarded_i+
                     project_signed_after_quickpay:competitively_awarded_i+
                             log(wins_project_quarter_stage)+
                     treat_i:post_t+
                     treat_i:post_t:competitively_awarded_i+
                     treat_i:post_t:project_signed_after_quickpay+
                     treat_i:post_t:project_signed_after_quickpay:competitively_awarded_i+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                                   action_date_year_quarter+
                       product_or_service_code,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

controls_and_all_fe=feglm(negative_delay~treat_i+
                                   project_signed_after_quickpay+
                                   competitively_awarded_i+
                             log(wins_project_quarter_stage)+
                     treat_i:competitively_awarded_i+
                     post_t:competitively_awarded_i+
                     project_signed_after_quickpay:competitively_awarded_i+
                     treat_i:post_t+
                     treat_i:post_t:competitively_awarded_i+
                     treat_i:post_t:project_signed_after_quickpay+
                     treat_i:post_t:project_signed_after_quickpay:competitively_awarded_i+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            number_of_offers_received+
                            post_t:number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)|
                                   action_date_year_quarter+
                       product_or_service_code+naics_code,
                           family='binomial',
                            cluster='contract_award_unique_key',
                           data=reg_df)

setFixest_dict(c("treat_i"="$Treat_i$",
                 "post_t"="$Post_t$",
                 "contract_financing_i"="$CF_i$",
                 "project_signed_before_quickpay"="$SB_i$",
                 "project_signed_after_quickpay"="$SA_i$",
                 "number_of_offers_received"="Number of offers received", 
                 "log(wins_project_quarter_stage)" = "Project stage",
                 "log(1+winsorized_initial_duration_in_days_i)" = "Initial duration",
                 "product_or_service_code"="Task code",
                 "log(1+winsorized_initial_budget_i)"="Initial budget",
                 "naics_code"="NAICS code",
                 "action_date_year_quarter"="Time",
                 "contract_award_unique_key"="Project ID",
                 "negative_delay"="$I(Delay<0)$",
                 "competitively_awarded_i"="$Competitive_i$"))

etable(baseline_reg,
       controls_and_no_fe,
       controls_and_time_fe,
       controls_time_task_fe,
       controls_and_all_fe,
       cluster = "contract_award_unique_key",
       title = "Logit model: Effect of QuickPay on Non-Competitive Projects",
       digits = "r2",
       tex=TRUE,
       drop=c('Initial budget',
              'Number of offers received',
              'Project stage',
              'Initial duration'),
       digits.stats = 2)
```