---
title: " Tobit Model: QuickPay (2009-2012)"
date: " `r format(Sys.time(), '%b %d, %Y')`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn,threeparttable}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(openxlsx)
library(tidyverse)
library(dplyr)
library(pryr)
library(lfe) # linear fixed effects 
library(DescTools) 
library(zoo) # for year quarter
library(stargazer)
library(broom)
library(data.table)
library(scales)
library(AER)
library(texreg)
```

```{r set_path_for_exporting, include=FALSE}
# tables_folder=paste0(getwd(),'/R_tables')
# figures_folder=paste0(getwd(),'/R_figures')
data_folder='~/Dropbox/data_quickpay/qp_data/'
```

```{r read_data, include=FALSE}
# Keep only projects whose start dates match with API one
projects_to_keep=fread(paste0(data_folder,'projects_to_keep.csv'))

# read quarterly resampled data
df=fread(paste0(data_folder,'resampled_qp_data/qp_resampled_data_fy10_to_fy12_with_zero_obs.csv'))
# specify date columns
date_cols=c("action_date_year_quarter","last_reported_start_date","last_reported_end_date")
df[,(date_cols):= lapply(.SD, as.Date), .SDcols = date_cols]

# restrict to quarter ending June 30, 2012
df=subset(df,as.Date(action_date_year_quarter)<max(as.Date('2012-07-01'))&
             contract_award_unique_key%in%projects_to_keep$contract_award_unique_key)
# data is truncated at July 1, 2012 -- 
# so quarter ending Sept 30, 2012 will only have values as of July 1, 2012

df_first_reported=fread(paste0(data_folder,'qp_data_first_reported.csv'))
# contains time-invariant contract characteristics -- info when contract first appeared in the data

```

```{r assign_variables_1, include=FALSE}
# Assign variables: Delay, Winsorized Delay, Post_t, Treat_i

# sort by contract id and date 
df=df[order(contract_award_unique_key,
            action_date_year_quarter)]

# determine quarter-to-quarter delay
df[,delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1), 
                  last_reported_end_date-lag(last_reported_end_date,1),NaN)]

# winsorize quarter-to-quarter delay
df[,winsorized_delay:=Winsorize(delay,na.rm=TRUE)]

#Post_t: A dummy that period t is post-treatment
df[,post_t:=ifelse(action_date_year_quarter>as.Date("2011-04-27"),1,0)]
# quickpay implemented on 27 April 2011. So all quarters starting 30 June 2011 will be in post-period

#Treat_i: A dummy that contract i is in the treatment group
df[,treat_i:=ifelse(business_type=="S",1,0)]
# quickpay was implemented for small business contracts

# Project age is a highly skewed variable
# assign number of quarters since project started: "project age" in some sense
df[, project_quarter_age := rowid(contract_award_unique_key)]
df[,project_quarter_tercile:=as.factor(ntile(project_quarter_age,3))]
# Including it as fixed effects doesn't work because projects in treatment and control are not always in same "tercile" while controling for everything else. 
```

```{r assign_variables_2, include=FALSE}

# ContractFinancing_i

df_first_reported[,contract_financing_i:=ifelse(!is.null(contract_financing_code)&
                                       !contract_financing_code%in%c("Z", ""),1,0)]

# Competition_i
df_first_reported[,competitively_awarded_i:=ifelse(!is.null(extent_competed_code)&
                                          !extent_competed_code%in%c("","G","B", "C","E"),1,0)]

# InitialDuration_i

df_first_reported[,initial_duration_in_days_i:=
                    as.numeric(
                    as.Date(period_of_performance_current_end_date)-
                    as.Date(period_of_performance_start_date))]

df_first_reported[,winsorized_initial_duration_in_days_i:=
                    Winsorize(as.numeric(
                    as.Date(period_of_performance_current_end_date)-
                    as.Date(period_of_performance_start_date)),na.rm=T)]

# InitialBudget_i

df_first_reported[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,na.rm=T)]

# Change type to string modification number
df_first_reported[,modification_number:=as.character(modification_number)]

select_cols=c("contract_award_unique_key",
              "recipient_duns",
              "naics_code",
              "product_or_service_code",
              "modification_number",
              "number_of_offers_received",
              "contract_financing_i",
              "competitively_awarded_i",
              "period_of_performance_start_date",
              "initial_duration_in_days_i",
              "winsorized_initial_duration_in_days_i",
              "winsorized_initial_budget_i")

# not necessary but speed efficient to set keys
setkey(df_first_reported[,..select_cols],
       contract_award_unique_key)
setkey(df,contract_award_unique_key)
```

```{r combine_dfs, include=FALSE}
# Combine all variables into dataframe needed for regression 
reg_df=merge(df,
             df_first_reported[,..select_cols],
             all.x = TRUE, # keep values in df, add columns of df_first_reported_cols
             by=c("contract_award_unique_key"))

# only keep observations with mod num zero
reg_df=subset(reg_df,modification_number=="0")

# sort by contract id and date (just to be doubly sure)
reg_df=reg_df[order(contract_award_unique_key,
            action_date_year_quarter)]

```

```{r percentage_delay,include=FALSE}

reg_df[,period_of_performance_start_date:=as.Date(period_of_performance_start_date)]

# get project duration as of last quarter in the denominator
reg_df[,percentage_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),
         delay/as.numeric(lag(last_reported_end_date,1)-lag(period_of_performance_start_date,1)),
         NaN)]

reg_df[,wins_percentage_delay:=Winsorize(100*percentage_delay,na.rm=T)]
```

```{r density_plots, eval=FALSE,include=FALSE}

hist(reg_df$wins_percentage_delay,freq=FALSE, main='Density plot: Full Sample')

left_censored_at_zero=subset(reg_df,wins_percentage_delay!=0)
hist(left_censored_at_zero$wins_percentage_delay,freq=FALSE, main='Density plot: Percentage Delay>0')

left_and_right_censored=subset(reg_df,wins_percentage_delay!=0 & wins_percentage_delay<177)
hist(left_and_right_censored$wins_percentage_delay,freq=FALSE, main='Density plot: 0<Percentage Delay<177')
```

```{r regressions,include=FALSE,echo=FALSE}
m1=AER::tobit(wins_percentage_delay ~ treat_i+
                post_t:treat_i+
                post_t,
              cluster=contract_award_unique_key,
              dist="logistic",
              left = 0,
              right=177,
              robust=T,
              data = reg_df)

m2=AER::tobit(wins_percentage_delay ~ treat_i+
                post_t:treat_i+
                post_t,
              cluster=contract_award_unique_key,
              dist="gaussian",
              left = 0,
              right=177,
              robust=T,
              data = reg_df)
```

```{r reg_output, results='asis', echo=FALSE}
texreg(list(m1,m2), 
       custom.model.names = c("Logistic","Gaussian"),
       custom.coef.names = c("Intercept",
        "$Treat_i$",
        "$Post_t$",
        "$Treat_i \\times Post_t$",
        "Log(scale)"),
         caption = "Tobit model", 
        # threeparttable = TRUE,
         custom.note="SEs are robust and clustered at the project level.",
        # label = "tab:5", 
        # dcolumn = TRUE, 
        # booktabs = TRUE, 
        # use.packages = FALSE, 
        # include.adjrs = FALSE, 
         include.bic = FALSE,
         include.aic=FALSE,
         digits = 2)
```