---
title: "Project level delays with Extended Sample"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(fixest)
library(DescTools)
library(data.table)
library(dplyr)
library(MatchIt)
library(zoo)
library(ggplot2)
library(ggpubr)
```

```{r read_data,include=FALSE}
full_df=fread('/Users/vibhutid_admin/Desktop/qp_data_new.csv')
```

```{r subset_data,include=FALSE}
full_df_tr=setDT(full_df[,c('contract_award_unique_key',
                      'contracting_officers_determination_of_business_size_code',
                      'period_of_performance_start_date',
                      'period_of_performance_current_end_date',
                      'action_date',
                      'naics_code',
                      'product_or_service_code',
                      'awarding_sub_agency_code',
                      'contract_financing_code',
                      'base_and_all_options_value',
                      'extent_competed_code',
                      'recipient_duns',
                      'action_type_code',
                      'number_of_offers_received',
                      'type_of_set_aside_code',
                      'type_of_set_aside',
                      'type_of_contract_pricing_code',
                      'type_of_contract_pricing',
                      'small_disadvantaged_business')])

full_df_tr[,price_structure:=case_when(type_of_contract_pricing_code%in%c('J','L','M','B','K','A')~"Fixed",
                                       type_of_contract_pricing_code%in%c('U','R','S','T','V')~"Cost")]
# date formats
full_df_tr[,action_date:=as.Date(action_date)]

full_df_tr[,period_of_performance_current_end_date:=
             as.Date(period_of_performance_current_end_date)]

full_df_tr[,period_of_performance_start_date:=
             as.Date(period_of_performance_start_date)]

full_df_tr=full_df_tr[action_date<=period_of_performance_current_end_date &
                        action_date>=period_of_performance_start_date]

# Action dates before July 1, 2012 --- QP extended to everyone after that
full_df_tr=full_df_tr[action_date<as.Date('2012-07-01')]

# Get initial and final dates
full_df_tr=full_df_tr[order(contract_award_unique_key,
                            action_date)]

dates=full_df_tr[,.(initial_end_date = first(period_of_performance_current_end_date), # first reported end date
                     eventual_end_date = last(period_of_performance_current_end_date),  # last reported end date
                     initial_start_date = first(period_of_performance_start_date),
                    initial_budget=first(base_and_all_options_value)), # first reported start date
                     by='contract_award_unique_key']

full_df_tr=merge(full_df_tr,
                 dates,
                 by='contract_award_unique_key',
                 all.x=T)
```

```{r variables, include=FALSE}
full_df_tr[,start_yr_qtr:=as.yearqtr(initial_start_date, format = "%Y-%m-%d")]

full_df_tr[,delay:=as.numeric(eventual_end_date-initial_end_date)]
full_df_tr[,positive_delay:=ifelse(delay>0,1,0)]
full_df_tr[,negative_delay:=ifelse(delay<0,1,0)]

full_df_tr[,initial_duration:=as.numeric(initial_end_date-initial_start_date)]
full_df_tr[,contract_financing_i:=ifelse(!is.null(contract_financing_code)&
                                                  !contract_financing_code%in%c("Z", ""),1,0)]

# Competition_i
full_df_tr[,competitively_awarded_i:=ifelse(!extent_competed_code%in%c("G","B", "C"),1,0)]

full_df_tr[,treat_i:=case_when(contracting_officers_determination_of_business_size_code=="S" &
                              small_disadvantaged_business=="f" ~ 1,
                              contracting_officers_determination_of_business_size_code=="O" &
                              small_disadvantaged_business=="f" ~ 0)]

# projects that start after QuickPay
# full_df_tr[,post_t:=ifelse(initial_start_date>as.Date('2011-04-27'),
#                               1,0)]

# projects that were slated to end after QuickPay
full_df_tr[,post_t:=ifelse(initial_end_date>as.Date('2011-04-27'),
                             1,0)]

full_df_tr[,relative_delay:=delay/(1+initial_duration)]
```

```{r clean_control, include=FALSE}
small_contractors=unique(subset(full_df_tr,treat_i==1)$recipient_duns)
large_contractors=unique(subset(full_df_tr,treat_i==0)$recipient_duns)

full_df_tr[,treat_new:=case_when(treat_i==1 ~ 1, # all small projects are 1
                             treat_i==0 & !(recipient_duns%in%small_contractors)~0, # only large projects w/o small project is zero
                             treat_i==0 & recipient_duns%in%small_contractors~NaN)]

```

```{r keep_api, include=FALSE}
# full_df_tr=subset(full_df_tr,
#                     contract_award_unique_key%in%projects_to_keep$contract_award_unique_key)

full_df_tr=full_df_tr[order(contract_award_unique_key,
                                action_date)]
# one observation per project...
full_df_tr=unique(full_df_tr,by='contract_award_unique_key')

full_df_tr[,wins_delay:=Winsorize(delay,probs=c(0.05,0.95),na.rm=T)]
full_df_tr[,wins_relative_delay:=Winsorize(relative_delay,probs=c(0.05,0.95),na.rm=T)]
# To fix zero duration and zero budget
full_df_tr[,wins_initial_duration:=Winsorize(initial_duration,probs=c(0.05,0.95),na.rm=T)]
full_df_tr[,wins_initial_budget:=Winsorize(initial_budget,probs=c(0.05,0.95),na.rm=T)]
full_df_tr[,wins_offers:=Winsorize(number_of_offers_received,probs=c(0.05,0.95),na.rm=T)]
```

```{r regs, include=FALSE}
m1=feols(wins_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
        #            cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m2=feols(wins_relative_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
        # cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m3=feglm(positive_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
             #       cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr, 
                  family = 'binomial')

m4=feglm(negative_delay~treat_i+
           post_t:treat_i+
           post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
       #  cluster=~contract_award_unique_key, # clustered at project level
         data=full_df_tr, 
         family = 'binomial')

main_results=list(m1,m2,m3,m4)
```

```{r clean_control_regs, include=FALSE}
m1=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
                  #  cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m2=feols(wins_relative_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
         #cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m3=feglm(positive_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr, 
                  family = 'binomial')

m4=feglm(negative_delay~treat_new+
           post_t:treat_new+
           post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
     #    cluster=~contract_award_unique_key, # clustered at project level
         data=full_df_tr, 
         family = 'binomial')

clean_control=list(m1,m2,m3,m4)
```

```{r cost_projects, include=FALSE}
m1=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
                  #  cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[price_structure=="Cost"])

m2=feols(wins_relative_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
         #cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[price_structure=="Cost"])

m3=feglm(positive_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[price_structure=="Cost"], 
                  family = 'binomial')

m4=feglm(negative_delay~treat_new+
           post_t:treat_new+
           post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
     #    cluster=~contract_award_unique_key, # clustered at project level
         data=full_df_tr[price_structure=="Cost"], 
         family = 'binomial')

cost_projects=list(m1,m2,m3,m4)
```

```{r other_than_fixed_price, include=FALSE}
m1=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
                  #  cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[!type_of_contract_pricing_code%in%c('J','L','M','B','K','A')])

m2=feols(wins_relative_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
         #cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[!type_of_contract_pricing_code%in%c('J','L','M','B','K','A')])

m3=feglm(positive_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[!type_of_contract_pricing_code%in%c('J','L','M','B','K','A')], 
                  family = 'binomial')

m4=feglm(negative_delay~treat_new+
           post_t:treat_new+
           post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
     #    cluster=~contract_award_unique_key, # clustered at project level
         data=full_df_tr[!type_of_contract_pricing_code%in%c('J','L','M','B','K','A')], 
         family = 'binomial')

other_than_fixed_price=list(m1,m2,m3,m4)
```

```{r sdb, include=FALSE}
full_df_tr[,sdb:=case_when(small_disadvantaged_business=="t" &
                             contracting_officers_determination_of_business_size_code=="S" ~1,
                           small_disadvantaged_business=="f" &
                             contracting_officers_determination_of_business_size_code=="O"&
                             !(recipient_duns%in%small_contractors)~0)]
m1=feols(wins_delay~sdb+
                    post_t:sdb+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
                  #  cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m2=feols(wins_relative_delay~sdb+
                    post_t:sdb+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
         #cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr)

m3=feglm(positive_delay~sdb+
                    post_t:sdb+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr, 
                  family = 'binomial')

m4=feglm(negative_delay~sdb+
           post_t:sdb+
           post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code+
           type_of_contract_pricing_code,
     #    cluster=~contract_award_unique_key, # clustered at project level
         data=full_df_tr, 
         family = 'binomial')

sdb=list(m1,m2,m3,m4)
```

```{r output, echo=FALSE,results='asis'}
setFixest_dict(c("wins_delay"="Delay days",
                 "start_yr_qtr"="Start Year-Quarter",
                 "wins_relative_delay"="Delay/Initial duration",
                 "treat_i"="Treat",
                 "treat_new"="Treat", # Clean control group
                 "post_t"="Post",
              "wins_initial_duration"="Initial duration",
              "wins_offers"="Number of offers",
              "positive_delay"="I(Delay>0)",
              "negative_delay"="I(Delay<0)",
              "product_or_service_code"="Task",
              "naics_code"="NAICS",
              "sdb"="Small-disadvantaged business",
              "recipient_duns"="Contractor",
              "awarding_sub_agency_code"="Sub-agency",
              "type_of_contract_pricing_code"="Pricing code",
              "contract_award_unique_key"="Project ID",
              "wins_initial_budget"="Initial budget"))

etable(main_results,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",4)),
       title="Full sample",
       digits='r2',
       tex=T)

etable(clean_control,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",4)),
       title="Clean control group",
              digits='r2',
       tex=T)

etable(cost_projects,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",4)),
       title="Cost projects",
              digits='r2',
       tex=T)

etable(other_than_fixed_price,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",4)),
       title="Other than fixed price projects",
              digits='r2',
       tex=T)

etable(sdb,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",4)),
       title="Small disadvantaged business",
              digits='r2',
       tex=T)
```

```{r positive_delay_only, include=FALSE}
m1=feols(wins_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[delay>0])

m2=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
             #       cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[delay>0])

positive_delay_only=list(m1,m2)
```

```{r action_type, include=FALSE}
# projects with action type other than "" or "M"
action_type_projs=unique(full_df_tr[!action_type_code%in%c("","M")]$contract_award_unique_key)
m1=feols(wins_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
                 #   cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[!(contract_award_unique_key%in%action_type_projs)])

m2=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
                #    cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[!(contract_award_unique_key%in%action_type_projs)])

action_type_only_m=list(m1,m2)
```

```{r no_set_aside, include=FALSE}
m1=feols(wins_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[type_of_set_aside_code%in%c("","NONE")])

m2=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
                 #   cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[type_of_set_aside_code%in%c("","NONE")])

no_set_aside=list(m1,m2)
```

```{r started_before_qp, include=FALSE}
m1=feols(wins_delay~treat_i+
                    post_t:treat_i+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
               #     cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[initial_start_date<as.Date('2011-04-27')])

m2=feols(wins_delay~treat_new+
                    post_t:treat_new+
                    post_t+ 
           wins_initial_duration+
           wins_initial_budget+
           wins_offers|start_yr_qtr+
                    product_or_service_code+
                    naics_code+
                    awarding_sub_agency_code,
              #      cluster=~contract_award_unique_key, # clustered at project level
                  data=full_df_tr[initial_start_date<as.Date('2011-04-27')])


started_before_qp=list(m1,m2)
```

```{r output_subsample,echo=FALSE,results='asis'}

etable(action_type_only_m,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
        extralines = list("Controls"=rep("Yes",2)),
       digits='r2',
       headers=c("All","Clean control"),
       title="Action type = M or N/A",
       tex=T)

etable(no_set_aside,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
        extralines = list("Controls"=rep("Yes",2)),
       digits='r2',
       headers=c("All","Clean control"),
       title="No set aside used",
       tex=T)

etable(started_before_qp,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",2)),
       digits='r2',
       headers=c("All","Clean control"),
       title="Projects that started before QuickPay",
       tex=T)

etable(positive_delay_only,
       drop=c("Number of offers",
              "Initial duration",
              "Initial budget"),
       extralines = list("Controls"=rep("Yes",2)),
       digits='r2',
       headers=c("All","Clean control"),
       title="Projects that had a positive delay only",
       tex=T)
```

