---
title: "Competition"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r competition_delays_subsample, echo=FALSE, results='asis', message=FALSE}
# Define
# $$ SA_i = \begin{cases} 1, \text{ if project was signed after QuickPay}\\
# 0, \text{ otherwise} \end{cases}$$

reg_df_subset[,project_signed_after_quickpay:=case_when(initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter>=as.Date('2011-04-27')~1,
                                                 initial_start_date<as.Date('2011-04-27') ~ 0,
                                                 initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter<as.Date('2011-04-27')~NaN)]
```

```{r define_contractor_controls,include=FALSE}
num_contractor_qtr_projects=reg_df_subset[,.(num_contractor_projects=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=reg_df_subset[wins_percentage_delay>0,.(num_projects_delayed=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=num_contractor_qtr_project_delays[order(recipient_duns,action_date_year_quarter)]

# Calculate how many projects of contractor were delayed until last quarter
num_contractor_qtr_project_delays[, num_delayed_until_last_qtr := shift(cumsum(num_projects_delayed),fill=0), by = recipient_duns]

num_contractor_qtr_projects=merge(num_contractor_qtr_projects,
                                  num_contractor_qtr_project_delays,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

num_contractor_qtr_projects[,num_projects_delayed:=ifelse(is.na(num_projects_delayed),0,num_projects_delayed)]

num_contractor_qtr_projects[,num_delayed_until_last_qtr:=ifelse(is.na(num_delayed_until_last_qtr),0,num_delayed_until_last_qtr)]


reg_df_subset=merge(reg_df_subset,
                    num_contractor_qtr_projects,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

reg_df_subset[,num_concurrent_contractor_projects:=num_contractor_projects-1]

```

```{r competition_subsample_ii, echo=FALSE, results='asis', message=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)+
          num_concurrent_contractor_projects+
          num_delayed_until_last_qtr|
                            action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          fixef.rm = "none",
                          data=subset(reg_df_subset,competitively_awarded_i==1))

m2=feols(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)+
          num_concurrent_contractor_projects+
          num_delayed_until_last_qtr|
                            product_or_service_code+
                            action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          fixef.rm = "none",
                          data=subset(reg_df_subset,competitively_awarded_i==1))

m3=feols(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)+
          num_concurrent_contractor_projects+
          num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter,
                          cluster=~contract_award_unique_key,
                          fixef.rm = "none",
                          data=subset(reg_df_subset,competitively_awarded_i==1))

m4=feols(wins_percentage_delay~treat_new+
                                project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)+
          num_concurrent_contractor_projects+
          num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
           recipient_duns,
                          cluster=~contract_award_unique_key,
                          fixef.rm = "none",
                          data=subset(reg_df_subset,competitively_awarded_i==1))

m5=feols(wins_percentage_delay~project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)+
          num_concurrent_contractor_projects+
          num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
           recipient_duns,
                          cluster=~contract_award_unique_key,
                          fixef.rm = "none",
                          data=subset(reg_df_subset,competitively_awarded_i==1))

#competition=list(m1,m2,m3,m4,m5)
competition=list(m1,m2,m3)

```

```{r output, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
invisible(capture.output(setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="$Post_t$",
                      "treat_new"="$Treat_i$",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "project_signed_after_quickpay"="$SA_i$",
                      "num_concurrent_contractor_projects"="NumConcurrent",
                      "num_delayed_until_last_qtr"="NumDelayed",
                      "recipient_duns"="Contractor"
                      ))))

etable(competition,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       caption="Effect of QuickPay on percentage delay rates (SE)",
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "NumConcurrent",
              "NumDelayed"),
       style.tex=style.tex(fixef.title = "\\midrule",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
               extralines=list("Contractor controls"=rep("Yes",length(competition))),
       notes="Additional controls not shown: Log(project stage). Contractor-level controls include the number of concurrent projects and the number of previously delayed projects.",
       tex=TRUE)

etable(competition,
       digits='r5',
       digits.stats = 2,
       fontsize = "small",
       caption="Effect of QuickPay on percentage delay rates (p-values)",
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "NumConcurrent",
              "NumDelayed"),
        coefstat = "pvalue",
       style.tex=style.tex(fixef.title = "\\midrule",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
               extralines=list("Contractor controls"=rep("Yes",length(competition))),
       notes="Additional controls not shown: Log(project stage). Contractor-level controls include the number of concurrent projects and the number of previously delayed projects.",
       tex=TRUE)
```