---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools)
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r define_contractor_controls,include=FALSE}
num_contractor_qtr_projects=reg_df_subset[,.(num_contractor_projects=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=reg_df_subset[wins_percentage_delay>0,.(num_projects_delayed=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=num_contractor_qtr_project_delays[order(recipient_duns,action_date_year_quarter)]

# Calculate how many projects of contractor were delayed until last quarter
num_contractor_qtr_project_delays[, num_delayed_until_last_qtr := shift(cumsum(num_projects_delayed),fill=0), by = recipient_duns]

num_contractor_qtr_projects=merge(num_contractor_qtr_projects,
                                  num_contractor_qtr_project_delays,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

num_contractor_qtr_projects[,num_projects_delayed:=ifelse(is.na(num_projects_delayed),0,num_projects_delayed)]

num_contractor_qtr_projects[,num_delayed_until_last_qtr:=ifelse(is.na(num_delayed_until_last_qtr),0,num_delayed_until_last_qtr)]


reg_df_subset=merge(reg_df_subset,
                    num_contractor_qtr_projects,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

reg_df_subset[,num_concurrent_contractor_projects:=num_contractor_projects-1]

```

```{r reg_without_controls, include=FALSE}

m0=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+post_t,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)
```

```{r regs_with_controls, include=FALSE}

m1=feols(wins_percentage_delay~treat_new+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+
                           product_or_service_code+
                           action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)


m2=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
           log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+
                   product_or_service_code+
                   action_date_year_quarter+
                   recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m4=feols(wins_percentage_delay~#treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

# m6=feols(wins_percentage_delay~#treat_new+
#             num_delayed_until_last_qtr+
#             num_concurrent_contractor_projects+
#                             post_t:treat_new+
#                             log(wins_project_quarter_stage)+
#                             # log(1+winsorized_initial_duration_in_days_i)+
#                             # log(1+winsorized_initial_budget_i)+
#                             # wins_number_of_offers_received+
#                             post_t:
#                 log(1+winsorized_initial_duration_in_days_i)+
#                             post_t:log(1+winsorized_initial_budget_i)+
#                             post_t:wins_number_of_offers_received|
#                             contract_award_unique_key+action_date_year_quarter,
#                             cluster=~contract_award_unique_key,
#                           data=reg_df_subset)

delay_rates=list(m1,m2,m3,m4)
```

```{r contractor_cluster_se, include=FALSE}

m1=feols(wins_percentage_delay~treat_new+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~recipient_duns,
                          data=reg_df_subset)


m2=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~recipient_duns,
                          data=reg_df_subset)


m3=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~recipient_duns,
                          data=reg_df_subset)

m4=feols(wins_percentage_delay~#treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~recipient_duns,
                          data=reg_df_subset)

m5=feols(wins_percentage_delay~#treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            # log(1+winsorized_initial_duration_in_days_i)+
                            # log(1+winsorized_initial_budget_i)+
                            # wins_number_of_offers_received+
                            post_t:
                log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            contract_award_unique_key+action_date_year_quarter,
                            cluster=~recipient_duns,
                          data=reg_df_subset)

contractor_cluster_delay_rates=list(m1,m2,m3,m4,m5)
```

```{r positive_delay_setup, include=FALSE}
reg_df_subset[,positive_delay:=ifelse(delay>0,1,0)]

reg_df_subset_positive=subset(reg_df_subset,delay>0)
reg_df_subset_positive[,wins_percentage_delay:=Winsorize(100*percentage_delay,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset_positive[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,
                                                              probs=c(0.05,0.95),
                                na.rm=T)]

reg_df_subset_positive[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i
reg_df_subset_positive[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_subset_positive[,wins_number_of_offers_received:=
                    Winsorize(number_of_offers_received,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]
```

```{r positive_delay_logit, eval=FALSE}
m1=feglm(positive_delay~treat_new+
            num_delayed_until_last_qtr+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2=feglm(positive_delay~treat_new+
                            post_t:treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feglm(positive_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m4=feglm(positive_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            family='binomial',
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

positive_delay_logit=list(m1,m2,m3,m4)
```

```{r conditional_delay_rates,include=FALSE}
m1=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m2=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m3=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m4=feols(wins_percentage_delay~treat_new+
            num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

m5=feols(wins_percentage_delay~num_delayed_until_last_qtr+
            num_concurrent_contractor_projects+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset_positive)

conditional_delay_rates=list(m1,m2,m3,m4,m5)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="$Post_t$",
                      "treat_new"="$Treat_i$",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency",
                      "num_concurrent_contractor_projects"="$NumConcurrent_{k(i)t}$",
            "num_delayed_until_last_qtr"="$NumPastDelays_{k(i)t}$",
            "recipient_duns"="Contractor"
                      ))

etable(m0,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Effect of QuickPay on percentage delay rates",
       fitstat = c("pr2","n","r2"),
       style.tex = style.tex(model.format = "I",
                             fixef.suffix = " FE",
                             stats.title = "",
                             var.title = "\\midrule",
                             fixef.title = "\\midrule",
                             line.top = 'simple',
                             line.bottom = 'simple',
                             yesNo = c("Yes","No"),
                             depvar.title = "",
                             model.title = ''),
       tex=TRUE)

etable(delay_rates,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Effect of QuickPay on percentage delay rates",
       headers=list("Average treatment effect"=length(delay_rates)),
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex = style.tex(model.format = "I",
                             fixef.suffix = " FE",
                             stats.title = "",
                             var.title = "\\midrule",
                             fixef.title = "\\midrule",
                             line.top = 'simple',
                             line.bottom = 'simple',
                             yesNo = c("Yes","No"),
                             depvar.title = "",
                             model.title = ''),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)

# etable(positive_delay_logit,
#        digits='r2',
#        digits.stats = 2,
#        fontsize = "small",
#        title="Effect of QuickPay on percentage delay rates",
#        headers=list("Delay likelihood"=length(positive_delay_logit)),
#        fitstat = c("pr2","n","r2"),
#        drop=c("Project stage",
#               "Initial duration",
#               "Initial budget",
#               "Number of offers"),
#        style.tex=style.tex(fixef.title = "\\midrule",
#                            fixef.suffix = " FE",
#                            var.title = "\\midrule ",
#                            depvar.title = "\\midrule ",
#                            model.title = "\\midrule ",
#                            stats.title = "",
#                            model.format = "I",
#                            yesNo = c("Yes","No"),
#                            line.bottom="simple",
#                            line.top="simple"),
#        notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
#        tex=TRUE)

etable(conditional_delay_rates,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Effect of QuickPay on percentage delay rates",
       headers=list("Conditional ATE"=length(conditional_delay_rates)),
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex = style.tex(model.format = "I",
                             fixef.suffix = " FE",
                             stats.title = "",
                             var.title = "\\midrule",
                             fixef.title = "\\midrule",
                             line.top = 'simple',
                             line.bottom = 'simple',
                             yesNo = c("Yes","No"),
                             depvar.title = "",
                             model.title = ''),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)


etable(contractor_cluster_delay_rates,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       title="Effect of QuickPay on percentage delay rates",
       headers=list("Average treatment effect"=length(contractor_cluster_delay_rates)),
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex = style.tex(model.format = "I",
                             fixef.suffix = " FE",
                             stats.title = "",
                             var.title = "\\midrule",
                             fixef.title = "\\midrule",
                             line.top = 'simple',
                             line.bottom = 'simple',
                             yesNo = c("Yes","No"),
                             depvar.title = "",
                             model.title = ''),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```


