---
title: "Bidding Metrics"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(zoo) # for year quarter
library(DescTools) 
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df=fread(paste0(input_path,
                 'quickpay_delays.csv'))
```

```{r competition_delays_subsample, echo=FALSE, results='asis'}
reg_df[,project_signed_after_quickpay:=case_when(initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter>=as.Date('2011-04-27')~1,
                                                 initial_start_date<as.Date('2011-04-27') ~ 0,
                                                 initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter<as.Date('2011-04-27')~NaN)]


reg_df[,quarter_when_project_signed:=as.Date(as.yearqtr(as.Date(initial_start_date)),
                                                       frac = 1)]

reg_df_first_reported=unique(reg_df,
                             by='contract_award_unique_key')

reg_df_first_reported=subset(reg_df_first_reported,
                             initial_start_date>as.Date('2009-12-31') & 
                               initial_start_date<as.Date('2012-03-31') &
                              competitively_awarded_i==1)
```

```{r competition_subsample_ii, echo=FALSE, results='asis'}
bids=feols(wins_number_of_offers_received~treat_i+
                                  treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed,
                          cluster=~contract_award_unique_key,
                          data=subset(reg_df_first_reported,
                                      number_of_offers_received>1 &
                                      number_of_offers_received<32)) 
       # remove outliers -- these are 0.1 and 0.99 quantile

duration=feols(winsorized_initial_duration_in_days_i~treat_i+
                                  treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed,
                          cluster=~contract_award_unique_key,
                          data=reg_df_first_reported)

budget=feols(I(winsorized_initial_budget_i/1000)~treat_i+
                                 treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed,
                          cluster=~contract_award_unique_key,
                          data=reg_df_first_reported)

bid_metrics=list(bids,
          duration,
          budget)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="$Post_t$",
                      "treat_i"="$Treat_i$",
                      "project_signed_after_quickpay"="$SA_i$",
                      "quarter_when_project_signed"="Time",
                      
                      "log(wins_project_quarter_stage)"="Project stage",
                      "winsorized_initial_duration_in_days_i"="Initial duration",
                      "I(winsorized_initial_budget_i/1000)"="Initial budget (000s)",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))

etable(bid_metrics,
       digits='r2',
       digits.stats = 2,
       fontsize = "small",
       caption="Bid metrics",
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex=style.tex(fixef.title = "\\midrule",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Sample restricted to competitively awarded projects",
       tex=TRUE)
```
