---
title: "Main Table - Excluding controls"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools)
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r delay_rates,include=FALSE}
m1=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m1_stage_post=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(wins_project_quarter_stage)+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2_stage_post=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(wins_project_quarter_stage)+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3_stage_post=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(wins_project_quarter_stage)+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m1_no_post_interaction=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received|
                            action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m2_no_post_interaction=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

m3_no_post_interaction=feols(wins_percentage_delay~treat_new+
                            post_t:treat_new+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)

delay_rates=list(m1,m2,m3)

stage_post=list(m1_stage_post,
                m2_stage_post,
                m3_stage_post)

no_post_interaction=list(m1_no_post_interaction,
                         m2_no_post_interaction,
                         m3_no_post_interaction)

```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "post_t"="Post",
                      "treat_new"="Treat",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency"
                      ))


etable(delay_rates,
       stage_post,
       no_post_interaction,
       digits='r2',
       digits.stats = 2,
       fontsize = "tiny",
       title="DiD with and without stage interaction",
       headers=list("Excluding Stage $\\times Post_t$"=length(delay_rates),
                    "Including Stage $\\times Post_t$"=length(stage_post),
                    "Excluding X $\\times Post_t$"=length(no_post_interaction)),
       fitstat = c("pr2","n","r2"),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       style.tex=style.tex(fixef.title = "",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "",
                           model.title = "",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Controls include Log(project stage), Log(1+initial duration), Log(1+initial budget), and number of bids. Log(1+initial duration), Log(1+initial budget), and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```


