---
title: "Alternative explanations"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array,makecell}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(DescTools)
library(fixest)
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))

df_first_reported=fread(paste0(data_folder,
                               'qp_data_first_reported.csv'))
```

```{r 8a_participants, include=FALSE}
get_vars=df_first_reported[,c('contract_award_unique_key',
                                      'c8a_program_participant',
                                      'type_of_set_aside',
                                      'sba_certified_8a_joint_venture',
                                      'receives_grants')]

reg_df_subset=merge(reg_df_subset,
                    get_vars,
                    by='contract_award_unique_key',
                    all.x=T)
```

```{r define_contractor_controls,include=FALSE}
num_contractor_qtr_projects=reg_df_subset[,.(num_contractor_projects=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=reg_df_subset[wins_percentage_delay>0,.(num_projects_delayed=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=num_contractor_qtr_project_delays[order(recipient_duns,action_date_year_quarter)]

# Calculate how many projects of contractor were delayed until last quarter
num_contractor_qtr_project_delays[, num_delayed_until_last_qtr := shift(cumsum(num_projects_delayed),fill=0), by = recipient_duns]

num_contractor_qtr_projects=merge(num_contractor_qtr_projects,
                                  num_contractor_qtr_project_delays,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

num_contractor_qtr_projects[,num_projects_delayed:=ifelse(is.na(num_projects_delayed),0,num_projects_delayed)]

num_contractor_qtr_projects[,num_delayed_until_last_qtr:=ifelse(is.na(num_delayed_until_last_qtr),0,num_delayed_until_last_qtr)]


reg_df_subset=merge(reg_df_subset,
                    num_contractor_qtr_projects,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

reg_df_subset[,num_concurrent_contractor_projects:=num_contractor_projects-1]

```


```{r non_c8a_regs, include=FALSE,warning=FALSE,message=FALSE}
## Non-C8A participants

non_c8a=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"&
                                       sba_certified_8a_joint_venture=="f"])

```


```{r no_set_aside, include=FALSE,warning=FALSE,message=FALSE}
## No set aside used

no_set_aside_used=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[type_of_set_aside%in%c("","NO SET ASIDE USED.")])
```


```{r no_grants,include=FALSE}
## Does not receive grants
contracts_receiving_grants=unique(reg_df_subset[receives_grants=='t']$
                                    recipient_duns)

no_grants=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[!(recipient_duns%in%
                                                 contracts_receiving_grants)])
```

```{r no_grants_8a_set_aside, include=FALSE}
no_grants_8a_set_aside=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[c8a_program_participant=="f"&
                                       sba_certified_8a_joint_venture=="f"&
                                         type_of_set_aside%in%
                                               c("","NO SET ASIDE USED.")&
                                               !(recipient_duns%in%
                                                 contracts_receiving_grants)])
```


```{r before_qp, include=FALSE}
## Started before QuickPay

projects_started_before_qp=unique(reg_df_subset[initial_start_date<
                                                  as.Date('2011-04-27')]$contract_award_unique_key)

projects_before_qp=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset[contract_award_unique_key%in%
                                               projects_started_before_qp])

```

```{r exclude_all, include=FALSE}
exclude_all=feols(wins_percentage_delay~#treat_new+
        treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
        log(wins_project_quarter_stage)+
        log(1+winsorized_initial_duration_in_days_i)+
        log(1+winsorized_initial_budget_i)+
        wins_number_of_offers_received+
        post_t:log(1+winsorized_initial_duration_in_days_i)+
        post_t:log(1+winsorized_initial_budget_i)+
        post_t:wins_number_of_offers_received|
        naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
      cluster=~contract_award_unique_key,
      data=reg_df_subset[c8a_program_participant=="f"&
                           sba_certified_8a_joint_venture=="f"&
                           type_of_set_aside%in%
                           c("","NO SET ASIDE USED.")&
                           !(recipient_duns%in%
                               contracts_receiving_grants) &
                           contract_award_unique_key%in%
                           projects_started_before_qp])
```


```{r jobs_act,include=FALSE,warning=FALSE,message=FALSE}
## Small business jobs act

# Jobs act = 1 if Date> Sept 30, 2010
# Jobs act was announced on Sept 27, 2010
# This variable is zero for only three quarters in our study period: Mar 31, 2010; June 30, 2010; and Sept 30, 2010.

reg_df_subset[,jobs_act:=ifelse(action_date_year_quarter>as.Date('2010-09-30'),
                                1,0)]

jobs_act_regs=feols(wins_percentage_delay~#treat_new+
                            treat_new:post_t+
                         num_delayed_until_last_qtr+
                           num_concurrent_contractor_projects+
                            treat_new:jobs_act+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter+recipient_duns,
                            cluster=~contract_award_unique_key,
                          data=reg_df_subset)
```

```{r export_results, echo=FALSE,results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percentage delay",
                      "post_t"="$Post_t$",
                      "treat_new"="$Treat_i$",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "recipient_duns"="Contractor",
                      "num_concurrent_contractor_projects"="$NumConcurrent_{k(i)t}$",
                    "num_delayed_until_last_qtr"="$NumPastDelays_{k(i)t}$",
                      "jobs_act"="After Jobs Act"
                      ))

etable(no_grants,
       no_set_aside_used,
       non_c8a,
       projects_before_qp,
       exclude_all,
       digits='r2',
       fontsize = 'tiny',
       caption="Alternative explanations",
       headers=list(" "=list(c("\\makecell{Excluding contractors \\\\
                    that receive grants}",
                    "\\makecell{Excluding set-aside \\\\ projects}",
                    "\\makecell{Excluding 8(A) \\\\ contractors}", 
                    "\\makecell{Excluding projects that\\\\ started after QuickPay}",
                    "\\makecell{Excluding all\\\\ preceding projects}"
                    ))),
       drop=c("Project stage",
              "Initial duration",
              "Initial budget",
              "Number of offers"),
       digits.stats = 2,
       style.tex=style.tex(fixef.title = "\\midrule ",
                           fixef.suffix = " FE",
                           var.title = "\\midrule ",
                           depvar.title = "\\midrule ",
                           model.title = "\\midrule ",
                           stats.title = "",
                           model.format = "I",
                           yesNo = c("Yes","No"),
                           line.bottom="simple",
                           line.top="simple"),
       notes="Controls include project stage, log of initial duration, log of initial budget, and number of bids. Initial duration, initial budget, and number of bids are also interacted with Post are also included as controls",
       tex=TRUE)
```
