---
title: "Main Table"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(fixest)
library(tidyverse)
library(DescTools)
```

```{r read_file_path, include=FALSE}
source("file_paths.R", 
       echo = F, 
       prompt.echo = "", 
       spaced = F)
```

```{r read_data,include=FALSE}
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r define_contractor_controls,include=FALSE}
num_contractor_qtr_projects=reg_df_subset[,.(num_contractor_projects=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=reg_df_subset[wins_percentage_delay>0,.(num_projects_delayed=n_distinct(contract_award_unique_key)),by=c('recipient_duns','action_date_year_quarter')]

num_contractor_qtr_project_delays=num_contractor_qtr_project_delays[order(recipient_duns,action_date_year_quarter)]

# Calculate how many projects of contractor were delayed until last quarter
num_contractor_qtr_project_delays[, num_delayed_until_last_qtr := shift(cumsum(num_projects_delayed),fill=0), by = recipient_duns]

num_contractor_qtr_projects=merge(num_contractor_qtr_projects,
                                  num_contractor_qtr_project_delays,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

num_contractor_qtr_projects[,num_projects_delayed:=ifelse(is.na(num_projects_delayed),0,num_projects_delayed)]

num_contractor_qtr_projects[,num_delayed_until_last_qtr:=ifelse(is.na(num_delayed_until_last_qtr),0,num_delayed_until_last_qtr)]


reg_df_subset=merge(reg_df_subset,
                    num_contractor_qtr_projects,
                    by=c('recipient_duns',
                         'action_date_year_quarter'),
                    all.x=T)

reg_df_subset[,num_concurrent_contractor_projects:=num_contractor_projects-1]

```

```{r regs_with_controls, include=FALSE}

m1=feols(wins_percentage_delay~treat_new:post_t+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                            log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received+
                            num_concurrent_contractor_projects+
                            num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
                            recipient_duns,
                            cluster=~recipient_duns,
                          data=reg_df_subset)

m2=feols(wins_percentage_delay~treat_new:post_t+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                            log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received+
                            num_concurrent_contractor_projects+
                            num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
                            recipient_duns,
                            cluster=~product_or_service_code,
                          data=reg_df_subset)

m3=feols(wins_percentage_delay~treat_new:post_t+
                            log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            post_t:
                            log(1+winsorized_initial_duration_in_days_i)+
                            post_t:log(1+winsorized_initial_budget_i)+
                            post_t:wins_number_of_offers_received+
                            num_concurrent_contractor_projects+
                            num_delayed_until_last_qtr|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter+
                            recipient_duns,
                            cluster=~naics_code,
                          data=reg_df_subset)

delay_rates=list(m1,m2,m3)
```

```{r output, echo=FALSE, results='asis'}
setFixest_dict(dict=c("wins_percentage_delay"="Percent delay rate",
                      "positive_delay"="Log odds (Delay rate >0)",
                      "post_t"="$Post_t$",
                      "treat_new"="$Treat_i$",
                      "log(wins_project_quarter_stage)"="Project stage",
                      "log(1+winsorized_initial_duration_in_days_i)"="Initial duration",
                      "log(1+winsorized_initial_budget_i)"="Initial budget",
                      "wins_number_of_offers_received"="Number of offers",
                      "contract_award_unique_key"="Project ID",
                      "product_or_service_code"="Task",
                      "action_date_year_quarter"="Time",
                      "naics_code"="Industry",
                      "awarding_sub_agency_code"="Subagency",
                      "num_concurrent_contractor_projects"="$NumConcurrent_{k(i)t}$",
            "num_delayed_until_last_qtr"="$NumPastDelays_{k(i)t}$",
            "recipient_duns"="Contractor"
                      ))

etable(delay_rates,
       digits = 'r2',
       digits.stats = 2,
       fontsize = "small",
       title = "Effect of QuickPay on percentage delay rates",
       headers = list("Average treatment effect" = length(delay_rates)),
       fitstat = c("pr2", "n", "r2"),
       drop = c("Project stage",
                "Initial duration",
                "Initial budget",
                "Number of offers",
                "%num_concurrent_contractor_projects",
                "%num_delayed_until_last_qtr"),
       style.tex = style.tex(
         model.format = "I",
         fixef.suffix = " FE",
         stats.title = "",
         var.title = "\\midrule",
         fixef.title = "\\midrule",
         line.top = 'simple',
         line.bottom = 'simple',
         yesNo = c("Yes","No"),
         depvar.title = "",
         model.title = ''
       ),
       extralines=list("__Cluster"=c("Contractor","Task", "Industry")),
       tex = TRUE)

```



