---
title: "QuickPay Delay Rate -- All Defense Projects"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(tidyverse)
library(dplyr)
library(pryr)
library(DescTools) 
library(zoo) # for year quarter
library(broom)
library(fixest)
library(data.table)
library(scales)
library(MatchIt)
```

```{r read_data,include=FALSE}
keep_cols=c('contract_award_unique_key',
            'period_of_performance_current_end_date',
            'period_of_performance_start_date',
            'contracting_officers_determination_of_business_size_code',
            'base_and_all_options_value',
            'action_date',
            'naics_code',
            'recipient_duns',
            'awarding_sub_agency_code',
            'product_or_service_code',
            'type_of_contract_pricing_code',
            'small_disadvantaged_business',
            'number_of_offers_received',
            'action_type',
            'action_type_code',
            'type_of_set_aside_code',
            'modification_number',
            'contract_financing_code',
            'extent_competed_code',
            'c8a_program_participant',
            'contract_bundling',
            'contract_bundling_code',
            'awarding_agency_code')

parent_folder='/Users/vibhutid_admin/Dropbox/USA_Spending_Downloads/award_data_archive_20200205/'
```

```{r}
parent_folder='/Users/vibhutid_admin/Dropbox/USA_Spending_Downloads/award_data_archive_20200205'
# Define the parent folder path

subfolders <- list.dirs(parent_folder, recursive = FALSE, full.names = TRUE)
subfolders <- subfolders[
  grepl("FY(2008|2009|2010|2011|2012|2013)", subfolders)
]

# Collect all CSV file paths from all subfolders
all_csvs <- list.files(
  path = subfolders,
  pattern = "\\.csv$",
  full.names = TRUE,
  recursive = TRUE
)

# Read and combine all CSVs
df <- rbindlist(
  lapply(
    all_csvs,
    fread,
    select = keep_cols
  ),
  use.names = TRUE,
  fill = TRUE
)

df=df[awarding_agency_code=='97']
```

```{r set_dates, include=FALSE}
df[,action_date:=as.Date(action_date)]
df[,period_of_performance_current_end_date:=as.Date(period_of_performance_current_end_date)]
df[,period_of_performance_start_date:=as.Date(period_of_performance_start_date)]
```

# QuickPay Expanded Sample

```{r select_projects, include=FALSE}
df=df[order(contract_award_unique_key,action_date)]

df[,two_digit_psc:=substr(product_or_service_code,1,2)]
df[,one_digit_psc:=substr(product_or_service_code,1,1)]

# only consider projects that started during this time
keep_ids=unique(df[modification_number%in%c(0,'0','P00000')]$contract_award_unique_key)

df=df[contract_award_unique_key%in%keep_ids]
```

```{r get_start_end_qtrs, include=FALSE}
# Get start and end quarters
start_end_dates=df[,.(first_action_date=first(action_date),
                      initial_start_date=
                        first(period_of_performance_start_date),
                      initial_end_date=
                        first(period_of_performance_current_end_date),
                      eventual_end_date=
                        last(period_of_performance_current_end_date),
                      last_action_date=last(action_date)),
                   by='contract_award_unique_key']

start_end_dates[,start_time:=as.Date(initial_start_date)]
# start_end_dates[,start_time:=fifelse(as.Date(first_action_date)<=
#                                        as.Date(initial_start_date),
#                                     as.Date(first_action_date),
#                                     as.Date(initial_start_date))]

start_end_dates[,end_time:=as.Date(eventual_end_date)]
#fifelse(as.Date(eventual_end_date)<=as.Date(last_action_date),
#                                   as.Date(eventual_end_date),
#                                   as.Date(last_action_date))]

start_end_dates[,start_quarter:=as.Date(as.yearqtr(start_time)+ 
                                          0.25) - 1]
start_end_dates[,end_quarter:=as.Date(as.yearqtr(end_time)+ 
                                        0.25) - 1]
```

```{r}
#2009-03 to 2012-03
#start_end_dates=start_end_dates[end_quarter>=as.Date('2009-03-31')&
#                                  start_quarter>=as.Date('2009-03-31')]
```

```{r}
# We are interested in the timeline from 2007-12-31 to 2013-12-31
timeline_start=as.Date('2008-03-31')
timeline_end=as.Date('2013-09-30') # Last date in the data

start_end_dates[, start_quarter:=case_when(start_quarter<timeline_start~
                                             timeline_start,
                                         start_quarter>timeline_end~
                                           timeline_end,
                                         start_quarter>=timeline_start &
                                         start_quarter<=timeline_end~
                                         start_quarter)]

start_end_dates[, end_quarter:=case_when(end_quarter<timeline_start~
                                             timeline_start,
                                         end_quarter>timeline_end~
                                           timeline_end,
                                         end_quarter>=timeline_start &
                                         end_quarter<=timeline_end~
                                         end_quarter)]

start_end_dates=start_end_dates[start_quarter<=end_quarter]

# Function to get list of quarters between two dates
get_quarters <- function(start, end) {
  quarters <- seq(from = start, to = end, by = "3 months")
  return(quarters)
}
```

```{r get_active_qtrs,include=FALSE}
# Get all active quarters 
# Get all quarters during which a project was active
# takes a few minutes to run
start_end_dates[, active_quarters := list(list(get_quarters(start_quarter, 
                                                            end_quarter))), 
                by = 1:nrow(start_end_dates)]

# Unnest the 'active_quarters' column
# We get all buyer-quarter observations
start_end_dates <- unnest(start_end_dates, active_quarters)

# Set as data table
start_end_dates=setDT(start_end_dates)

# Fix the quarter date formats
# Some have 30th as the last date when it should be 31st
start_end_dates[,active_quarters:=fifelse(format(active_quarters,"%m")%in%
                                            c('01','03','05','07','08','10','12') &
                                            format(active_quarters,"%d")=='30',
                                          active_quarters+1,
                                          active_quarters)]

# Some have 01 as the date when it should be end of preceding month
# E.g., 2010-09-30 instead of 2010-10-01
start_end_dates[,active_quarters:=fifelse(format(active_quarters,"%d")=='01',
                                          active_quarters-1,
                                          active_quarters)]

start_end_dates=start_end_dates[,c('contract_award_unique_key','active_quarters')]
setnames(start_end_dates,'active_quarters','action_date_year_quarter')

df[,action_date_year_quarter:=as.Date(as.yearqtr(action_date)+ 0.25) - 1]
df[,action_date_year_quarter:=fifelse(format(action_date_year_quarter,"%m")%in%
                                        c('01','03','05','07','08','10','12') &
                                        format(action_date_year_quarter,"%d")=='30',
                                      action_date_year_quarter+1,
                                      action_date_year_quarter)]

df[,action_date_year_quarter:=fifelse(format(action_date_year_quarter,"%d")=='01',
                                      action_date_year_quarter-1,
                                      action_date_year_quarter)]
```

```{r get_last_reported_dates,include=FALSE}

last_reported=df[,.(last_reported_end_date=
                      last(period_of_performance_current_end_date)),
                 by=c('contract_award_unique_key',
                      'action_date_year_quarter')]

start_end_dates=merge(start_end_dates,
                      last_reported,
                      by=c('contract_award_unique_key',
                           'action_date_year_quarter'),
                      all.x=T)

start_end_dates=start_end_dates[order(contract_award_unique_key,
                                      action_date_year_quarter)]
# For N/A dates, take the most recently reported one by project ID
start_end_dates[ , last_reported_end_date := 
                   nafill(last_reported_end_date, type = 'locf'), 
                   contract_award_unique_key]

```

```{r get_first_info,include=FALSE}
df=df[order(contract_award_unique_key,action_date)]

df_first=df[,.(initial_end_date = first(period_of_performance_current_end_date), 
               eventual_end_date = last(period_of_performance_current_end_date),
               initial_start_date = first(period_of_performance_start_date),
               initial_budget=first(base_and_all_options_value),
               type_of_contract_pricing_code=first(type_of_contract_pricing_code),
               awarding_sub_agency_code=first(awarding_sub_agency_code),
               product_or_service_code=first(product_or_service_code),
               naics_code=first(naics_code),
               contracting_officers_determination_of_business_size_code=
               first(contracting_officers_determination_of_business_size_code),
               recipient_duns=first(recipient_duns),
               small_disadvantaged_business=first(small_disadvantaged_business),
               number_of_offers_received=first(number_of_offers_received),
               type_of_set_aside_code=first(type_of_set_aside_code),
               extent_competed_code=first(extent_competed_code),
               contract_financing_code=first(contract_financing_code),
               c8a_program_participant=first(c8a_program_participant),
               contract_bundling=first(contract_bundling),
               contract_bundling_code=first(contract_bundling_code)),
            by='contract_award_unique_key']

df_first[,initial_duration:=as.numeric(initial_end_date-initial_start_date)]

df_first[,price_structure:=case_when(type_of_contract_pricing_code
                                     %in%c('J','L','M','B','K','A')~"Fixed",
                                     type_of_contract_pricing_code
                                     %in%c('U','R','S','T','V')~"Cost")]

df_first[,treat_i:=case_when(contracting_officers_determination_of_business_size_code=="S" &
                               small_disadvantaged_business=="f" ~ 1,
                             contracting_officers_determination_of_business_size_code=="O" &
                               small_disadvantaged_business=="f" ~ 0)]
```

```{r set_vars,include=FALSE}
reg_df=merge(start_end_dates,
             df_first,
             by='contract_award_unique_key',
             all.x=T)
```

```{r restrict_code, include=FALSE}
nanda_naics=c("3329",
  "2362",
  "2379",
  "5311",
  "5612",
  "5629",
  "5415",
  "4831",
  "6114",
  "4812",
  "3149",
  "3325",
  "1153",
  "3333",
  "4247",
  "3159",
  "3162",
  "3169",
  "3366",
  "3112")

reg_df[,four_digit_naics:=substr(naics_code,1,4)]
reg_df[,action_date_year_quarter:=as.Date(action_date_year_quarter)]
reg_df=reg_df[four_digit_naics%in%nanda_naics]
```

```{r delays}
reg_df=reg_df[order(contract_award_unique_key,action_date_year_quarter)]

reg_df[,delay:=fifelse(contract_award_unique_key==lag(contract_award_unique_key),
                       as.numeric(last_reported_end_date-
                                    lag(last_reported_end_date)),
                       NaN)]
reg_df[,wins_delay:=Winsorize(delay,probs=c(0.025,0.975),na.rm=T)]
reg_df[,wins_initial_duration:=Winsorize(initial_duration,probs=c(0.05,0.95),na.rm=T)]
reg_df[,wins_initial_budget:=Winsorize(initial_budget,probs=c(0.05,0.95),na.rm=T)]
reg_df[,wins_offers:=Winsorize(number_of_offers_received,probs=c(0.05,0.95),na.rm=T)]
reg_df[,relative_delay:=delay/(1+initial_duration)]
reg_df[,wins_relative_delay:=Winsorize(relative_delay,probs=c(0.025,0.975),na.rm=T)]
reg_df[,post_t:=fifelse(action_date_year_quarter>=as.Date('2011-04-27'),1,0)]
reg_df[,positive_delay:=ifelse(delay>0,1,0)]
reg_df[,negative_delay:=ifelse(delay<0,1,0)]

reg_df[,project_quarter_stage:=ifelse(contract_award_unique_key==
                                        lag(contract_award_unique_key,1),
                                      as.numeric(lag(action_date_year_quarter,1)-
                                                   initial_start_date)/as.numeric(lag(last_reported_end_date,1)-
                                                                                    initial_start_date),
                                      NaN)]

reg_df[,wins_project_quarter_stage:=100*Winsorize(project_quarter_stage,  
                                              na.rm=T)]
```

```{r pc_delay, include=FALSE}
reg_df[,last_reported_duration:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),
                                      as.numeric(lag(last_reported_end_date,1)-initial_start_date),
                                      initial_duration)]

# "period_of_performance_start_date" here comes from first reported info
# So it is the actual start date for a project
# get project duration as of last quarter in the denominator
reg_df[,percentage_delay:=ifelse(contract_award_unique_key==lag(contract_award_unique_key,1),
         delay/(1+last_reported_duration),
         NaN)]

reg_df[,wins_percentage_delay:=Winsorize(100*percentage_delay,                    
                              probs=c(0.025,0.975),
                              na.rm=T)]
```

```{r clean_control,include=FALSE}
small_contractors=unique(subset(reg_df,treat_i==1)$recipient_duns)
large_contractors=unique(subset(reg_df,treat_i==0)$recipient_duns)

reg_df[,treat_new:=case_when(treat_i==1 ~ 1,
                             treat_i==0 & !(recipient_duns%in%small_contractors)~0,
                             treat_i==0 & recipient_duns%in%small_contractors~NaN)]
```


```{r export_file, include=FALSE}
# saveRDS(reg_df, 
#          file = "/Users/vibhutid_admin/Desktop/Research/QuickPay/Data-and-code/replication_codes_v1/code/qp_revision/w_qp_timeline_2007_2013.rds")
```

```{r}
reg_fp=reg_df[type_of_contract_pricing_code=="J" &
                 !is.na(treat_new)
              ]
```

```{r}
pre_qp_small=mean(reg_fp[post_t==0 & treat_new==1]$wins_percentage_delay,
                 na.rm=T)

pre_qp_large=mean(reg_fp[post_t==0 & treat_new==0]$wins_percentage_delay,
                 na.rm=T)

plot_df=reg_fp[,
   .(avg_delay=mean(wins_percentage_delay,na.rm=T)),
   by=c('treat_new',
        'action_date_year_quarter')]

plot_df[,demeaned_delay:=case_when(treat_new==1~avg_delay-pre_qp_small,
                                treat_new==0~avg_delay-pre_qp_large)]

plot_df[, treat_group := fifelse(treat_new == 1, "Treated", "Control")]
plot_df[, treat_group := factor(treat_group, levels = c("Control", "Treated"))]

```

```{r}
cut_q1 <- "2011-03-31" 
# QP launched for SB: Apr 27, 2011
cut_q2 <- "2012-09-30"
# QP for LB: July 11, 2012
cut_q3 <- "2013-03-31"
# QP for SB: Feb 21, 2013

x1 <- which(levels(factor(plot_df$action_date_year_quarter)) == cut_q1) + 0.75
x2 <- which(levels(factor(plot_df$action_date_year_quarter)) == cut_q2) - 0.5
x3 <- which(levels(factor(plot_df$action_date_year_quarter)) == cut_q3) - 0.25

ymin <- min(plot_df$demeaned_delay, na.rm = TRUE)

ggplot(
  plot_df,
  aes(
    x = factor(action_date_year_quarter),
    y = demeaned_delay,
    group = treat_group,
    linetype = treat_group,
    shape = treat_group
  )
) +
  geom_point(size = 2) +
  geom_line(linewidth = 0.9) +
  geom_vline(xintercept = x1, 
             color = "darkred", 
             linewidth = 0.6) +
  geom_vline(xintercept = x2, 
             color = "darkred", 
             linewidth = 0.6) +
  geom_vline(xintercept = x3, 
             color = "darkred", 
             linewidth = 0.6) +
  scale_linetype_manual(
    values = c("Control" = "dashed", "Treated" = "solid")
  ) +
  scale_shape_manual(
    values = c("Control" = 17, "Treated" = 16)
  ) +

  theme_minimal() +
  labs(
    x = "Time",
    y = "Percentage delay rate \n (demeaned)",
    linetype = "",
    shape = ""
  ) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "bottom",
    legend.key.width = unit(3, "cm")
  ) +
  coord_fixed(ratio = 1)

```

```{r}
```