---
title: "Project Stage"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

```{r parallel_trends_test, echo=FALSE, results='asis'}
df_qn<-unique(reg_df_subset,by='action_date_year_quarter')[,"action_date_year_quarter"]
df_qn=df_qn[order(action_date_year_quarter)][,quarter_number:=seq.int(nrow(df_qn))]
reg_df_subset=merge(reg_df_subset,df_qn,by='action_date_year_quarter')

# Baseline Regressions 
m1=felm(wins_percentage_delay~treat_new+
                     quarter_number:treat_new+
                    quarter_number|
                    0| # no fixed effects
                    0| # no IV
                    contract_award_unique_key, # clustered at project level
                  data=subset(reg_df_subset, post_t==0),
                  exactDOF = TRUE, 
                  cmethod = "reghdfe")

# time fixed effects also included in the following specs

m2=felm(wins_percentage_delay~treat_new+
                           quarter_number:treat_new+
                           quarter_number+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            quarter_number:log(1+winsorized_initial_duration_in_days_i)+
                            quarter_number:log(1+winsorized_initial_budget_i)+
                            quarter_number:wins_number_of_offers_received|
                            0|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset, post_t==0),
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
# time fixed effects also included in the following specs
m3=felm(wins_percentage_delay~treat_new+
                             quarter_number:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            quarter_number:log(1+winsorized_initial_duration_in_days_i)+
                            quarter_number:log(1+winsorized_initial_budget_i)+
                            quarter_number:wins_number_of_offers_received|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset, post_t==0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
m4=felm(wins_percentage_delay~treat_new+
                              quarter_number:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            quarter_number:log(1+winsorized_initial_duration_in_days_i)+
                            quarter_number:log(1+winsorized_initial_budget_i)+
                            quarter_number:wins_number_of_offers_received|
                            product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset, post_t==0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
m5=felm(wins_percentage_delay~treat_new+
                            quarter_number:treat_new+
                           log(wins_project_quarter_stage)+
                            log(1+winsorized_initial_duration_in_days_i)+
                            log(1+winsorized_initial_budget_i)+
                            wins_number_of_offers_received+
                            quarter_number:log(1+winsorized_initial_duration_in_days_i)+
                            quarter_number:log(1+winsorized_initial_budget_i)+
                            quarter_number:wins_number_of_offers_received|
                            naics_code+product_or_service_code+action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset, post_t==0), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")

pt=stargazer(m1,m2,m3,m4,m5,
          title = "Linear Time Trend Before QuickPay",
          dep.var.labels="$PercentDelay_{it}$",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$","$QuarterNum$","$Treat_i \\times QuarterNum$","Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          digits=2,
          digits.extra=2,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Duration, Budget, Bids","No",rep("Yes",4)),
                           c("$Post_t \\times$  (Duration, Budget, Bids)","No",rep("Yes",4)),
                           c("Project stage","No",rep("Yes",4)),
                           c("Time fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Industry fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'wins_number_of_offers_received',
                   'quarter_number:winsorized_initial_duration_in_days_i',
                   'quarter_number:winsorized_initial_budget_i',
                   'quarter_number:wins_number_of_offers_received',
                   'wins_project_quarter_stage'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level.",
                  "Observations are for quarters before quickpay."),
          header=F)
```