---
title: "Competition"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

Define
$$ SA_i = \begin{cases} 1, \text{ if project was signed after QuickPay}\\
0, \text{ otherwise} \end{cases}$$

```{r competition_delays_subsample, echo=FALSE, results='asis'}
reg_df_subset[,project_signed_after_quickpay:=case_when(initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter>=as.Date('2011-04-27')~1,
                                                 initial_start_date<as.Date('2011-04-27') ~ 0,
                                                 initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter<as.Date('2011-04-27')~NaN)]
```

```{r competition_subsample_ii, echo=FALSE, results='asis'}

baseline_reg=felm(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                                  post_t|
                                  0| # no fixed effects
                                  0| # no IV
                                  contract_award_unique_key, # clustered at project level
                                  data=subset(reg_df_subset,competitively_awarded_i==1),
                                  exactDOF = TRUE,
                                  cmethod = "reghdfe")
controls_and_no_fe=felm(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                                  post_t+
                            log(wins_project_quarter_stage)|
                            0|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset,competitively_awarded_i==1), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_time_fe=felm(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)|
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset,competitively_awarded_i==1), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_time_task_fe=felm(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)|
                            product_or_service_code+
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset,competitively_awarded_i==1), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
controls_and_all_fe=felm(wins_percentage_delay~treat_new+
                                  project_signed_after_quickpay+
                                  treat_new:post_t+
                                  treat_new:post_t:project_signed_after_quickpay+
                            log(wins_project_quarter_stage)|
                            naics_code+
                            product_or_service_code+
                            action_date_year_quarter|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_subset,competitively_awarded_i==1), 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")
competitive_projects_table_ii=stargazer(controls_and_no_fe,
          controls_and_time_fe,
          controls_time_task_fe,
          controls_and_all_fe,
          digits=2,
          digits.extra=2,
          title = "Effect of QuickPay on competitively awarded projects",
          dep.var.labels="$PercentDelay_{it}$  ",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$",
                               "$SA_i$",
                               "$Post_t$",
                               "$Treat_i \\times Post_t$",
                               "$Treat_i \\times Post_t \\times SA_i $",
                               "Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(
                           c("Project stage",rep("No",1),rep("Yes",4)),
                           c("Time fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Industry fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('wins_project_quarter_stage'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level.",
                  "Sample restricted to fully competed projects."),
          header=F)
```
