---
title: "Congestion"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
input_path='~/Dropbox/data_quickpay/qp_replication/input/'
reg_df=fread(paste0(input_path,
                 'quickpay_delays.csv'))
```

```{r contractor_one_type,include=FALSE}
one_type_contractors=reg_df[,n_distinct(treat_i),by='recipient_duns']
one_type_contractors=unique(subset(one_type_contractors,V1==1 &
                                     !is.na(recipient_duns))$recipient_duns)

reg_df_one_type=subset(reg_df,recipient_duns%in%one_type_contractors)

reg_df_one_type[,wins_percentage_delay:=Winsorize(100*percentage_delay,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_one_type[,wins_project_quarter_stage:=Winsorize(project_quarter_stage,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]

reg_df_one_type[,winsorized_initial_duration_in_days_i:=
                    Winsorize(initial_duration_in_days_i,
                    probs=c(0.05,0.95),
                    na.rm=T)]

# InitialBudget_i

reg_df_one_type[,winsorized_initial_budget_i:=
                    Winsorize(base_and_all_options_value,                    
                              probs=c(0.05,0.95),
                              na.rm=T)]
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

# Congestion Effect

## Number of projects per contractor

* Contractors holding only small or only large projects

```{r num_projects_0,warning=FALSE, echo=FALSE, results='asis'}

active_before_qp=unique(subset(reg_df,post_t==0)$recipient_duns)
contractor_quarter=reg_df_one_type[,n_distinct(contract_award_unique_key),by=c('recipient_duns',
                                                            'action_date_year_quarter')]
setnames(contractor_quarter,'V1','num_projects')
contractor_quarter[,post_t:=ifelse(action_date_year_quarter>as.Date('2011-04-27'),1,0)]

contractor_quarter=merge(contractor_quarter,
                         unique(reg_df_one_type[,c('recipient_duns','treat_i')]),
                         by='recipient_duns')

contractor_quarter[,business_type:=ifelse(treat_i==1,"S","O")]

m1=felm(num_projects~treat_i+
          post_t:treat_i+post_t|
          0| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

m2=felm(num_projects~treat_i+
          post_t:treat_i|
          action_date_year_quarter| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

num_projects_table=stargazer(m1,m2,
          digits=2,
          digits.extra=2,
          title = "Num Contractor Projects and QuickPay reform",
          dep.var.labels="Number of projects",
          dep.var.caption = "",
          covariate.labels =c("$Treat_i$",
                               "$Post_t$",
                               "$Treat_i \\times Post_t$",
                               "Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Time fixed effects",rep("No",1),rep("Yes",1))),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a contractor-quarter.",
                  "SEs are robust and clustered at the contractor level.",
                  "Sample restricted to contractors performing only one type of project."),
          header=F)
```

## Budget

```{r budget_0,warning=FALSE, echo=FALSE, results='asis'}
contractor_quarter=reg_df_one_type[,sum(winsorized_initial_budget_i),
                                   by=c('recipient_duns',
                                        'action_date_year_quarter')]
setnames(contractor_quarter,'V1','total_budget_across_projects')
contractor_quarter[,post_t:=ifelse(action_date_year_quarter>as.Date('2011-04-27'),1,0)]

contractor_quarter=merge(contractor_quarter,
                         unique(reg_df_one_type[,c('recipient_duns','treat_i')]),
                         by='recipient_duns')

contractor_quarter[,business_type:=ifelse(treat_i==1,"S","O")]

m1=felm(I(total_budget_across_projects/1000000)~treat_i+
          post_t:treat_i+post_t|
          0| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

m2=felm(I(total_budget_across_projects/1000000)~treat_i+
          post_t:treat_i|
          action_date_year_quarter| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

congestion_budget_table=stargazer(m1,m2,
          digits=2,
          digits.extra=2,
          title = "Contractor Project Budget and QuickPay reform",
          dep.var.labels="Total budget (000,000s)",
          dep.var.caption = "",
          covariate.labels =c("$Treat_i$",
                               "$Post_t$",
                               "$Treat_i \\times Post_t$",
                               "Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Time fixed effects",rep("No",1),rep("Yes",1))),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a contractor-quarter.",
                  "SEs are robust and clustered at the contractor level.",
                  "Sample restricted to contractors performing only one type of project."),
          header=F)
```

## Number of tasks

```{r tasks_0,warning=FALSE, echo=FALSE, results='asis'}
contractor_quarter=reg_df_one_type[,n_distinct(product_or_service_code),
                                   by=c('recipient_duns',
                                        'action_date_year_quarter')]
setnames(contractor_quarter,'V1','number_of_tasks')
contractor_quarter[,post_t:=ifelse(action_date_year_quarter>as.Date('2011-04-27'),1,0)]

contractor_quarter=merge(contractor_quarter,
                         unique(reg_df_one_type[,c('recipient_duns','treat_i')]),
                         by='recipient_duns')

contractor_quarter[,business_type:=ifelse(treat_i==1,"S","O")]

m1=felm(number_of_tasks~treat_i+
          post_t:treat_i+post_t|
          0| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

m2=felm(number_of_tasks~treat_i+
          post_t:treat_i|
          action_date_year_quarter| # no fixed effects
          0| # no IV
          recipient_duns, # clustered at the contractor level
        data=contractor_quarter,
        exactDOF = TRUE, 
        cmethod = "reghdfe")

congestion_tasks_table=stargazer(m1,m2,
          digits=2,
          digits.extra=2,
          title = "Contractor Project Tasks and QuickPay reform",
          dep.var.labels="Number of tasks",
          dep.var.caption = "",
          covariate.labels =c("$Treat_i$",
                               "$Post_t$",
                               "$Treat_i \\times Post_t$",
                               "Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(c("Time fixed effects",rep("No",1),rep("Yes",1))),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a contractor-quarter.",
                  "SEs are robust and clustered at the contractor level.",
                  "Sample restricted to contractors performing only one type of project."),
          header=F)
```
