---
title: "Bidding Metrics"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(zoo) # for year quarter
library(DescTools) 
```

```{r read_data,include=FALSE}
input_path='~/Dropbox/data_quickpay/qp_replication/input/'
reg_df=fread(paste0(input_path,
                 'quickpay_delays.csv'))
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

```{r competition_delays_subsample, echo=FALSE, results='asis'}
reg_df[,project_signed_after_quickpay:=case_when(initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter>=as.Date('2011-04-27')~1,
                                                 initial_start_date<as.Date('2011-04-27') ~ 0,
                                                 initial_start_date>=as.Date('2011-04-27') &
                                                   action_date_year_quarter<as.Date('2011-04-27')~NaN)]


reg_df[,quarter_when_project_signed:=as.Date(as.yearqtr(as.Date(initial_start_date)),
                                                       frac = 1)]

reg_df_first_reported=unique(reg_df,
                             by='contract_award_unique_key')

reg_df_first_reported=subset(reg_df_first_reported,
                             initial_start_date>as.Date('2009-12-31') & 
                               initial_start_date<as.Date('2012-03-31') &
                              competitively_awarded_i==1)
```

```{r competition_subsample_ii, echo=FALSE, results='asis'}
bids=felm(wins_number_of_offers_received~treat_i+
                                  treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed|
                            0|
                            contract_award_unique_key,
                          data=subset(reg_df_first_reported,
                                      number_of_offers_received>1 &
                                      number_of_offers_received<32), 
                          # remove outliers -- these are 0.1 and 0.99 quantile
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")

duration=felm(winsorized_initial_duration_in_days_i~treat_i+
                                  treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed|
                            0|
                            contract_award_unique_key,
                          data=reg_df_first_reported, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")

budget=felm(I(winsorized_initial_budget_i/1000)~treat_i+
                                 treat_i:project_signed_after_quickpay|
                            product_or_service_code+
                            quarter_when_project_signed|
                            0|
                            contract_award_unique_key,
                          data=reg_df_first_reported, 
                          exactDOF = TRUE, 
                          cmethod = "reghdfe")

bidding_metrics_table=stargazer(bids,
          duration,
          budget,
          digits=2,
          digits.extra=2,
          title = "Effect of Competition After QuickPay: Quickpay 2009-2011",
          dep.var.labels=c("$NumberOfBids_{it}$",
                           "$InitialDuration_{it}$",
                           "$InitialBudget_{it}$ (000s)"),
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$",
                               "$Treat_i \\times Post_t$"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "0pt",
          add.lines = list(c("Task fixed effects",rep("Yes",3)),
                           c("Time fixed effects",rep("Yes",3))),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level.",
                  "Sample restricted to fully competed projects."),
          header=F)
```
