---
title: "Project Stage"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    keep_tex: false
    number_sections: true
header-includes:
 \usepackage{booktabs,longtable,dcolumn}
 \usepackage{multirow,array}
 \usepackage{wrapfig,float}
 \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages,warning=FALSE,message=FALSE,include=FALSE}
library(data.table)
library(dplyr)
library(lfe)
library(stargazer)
library(fixest)
library(tidyverse)
library(DescTools) 
```

```{r read_data,include=FALSE}
working_path='~/Dropbox/data_quickpay/qp_replication/working/'
reg_df_subset=fread(paste0(working_path,
                 'w_clean_control.csv'))
```

```{r stargazer_format, include=FALSE}
# Code to extract only the inner part (nested within tabular) of table from stargazer
# We will use this along with threeparttable in latex later 
# Code adapted from Patrick Baylis's blog on the topic:
# https://www.patrickbaylis.com/blog/2019-11-25-r-reg-tables/
make_tex_pieces <- function(stargazer_output) {
  # Split up into header, footer, and inner
  idx0 <- grep("begin{tabular}", stargazer_output, fixed = T) # Start of \begin{tabular}
  idx1 <- grep("end{tabular}", stargazer_output, fixed = T) # End of \begin{tabular}
  idx2<-grep("Adjusted",stargazer_output,fixed=T)
  
  tex_header <- c(stargazer_output[idx0],"\\toprule")
  tex_footer <- c("\\bottomrule", stargazer_output[idx1])
  tex_inner<-c(stargazer_output[(idx0+3):idx2])
  
  # Remove [-1.8ex] and replace \hline with \midrule
  tex_inner <- gsub("\\\\[-[\\.0-9]+ex]", "", tex_inner)
  
  tex_inner <- gsub("\\hline ", "\\midrule", tex_inner)
  # Return these as a 3 element list so that the user can insert header rows (column labels)
  # and footer rows (summary statistics, fixed effects)
  # list(header = tex_header, inner = tex_inner, footer = tex_footer)
  c(tex_header,tex_inner,tex_footer)
}
```

# Project Stage

* $t$ indicates the end of the quarter
* We want to get stage of the project at the beginning of a given quarter (before any delays materialize)

$Stage_{it}=\frac{ActionDate_{t-1}-StartDate_i}{Duration_{i,t-1}}$
$Stage_{it}=\frac{(t-1)-StartDate_i}{Duration_{i,t-1}}$
```{r stage_regs_log, warning=FALSE, echo=FALSE, results='asis'}

m1=felm(wins_percentage_delay~treat_new+
          log(wins_project_quarter_stage)+
          post_t:treat_new+
          treat_new:log(wins_project_quarter_stage)+
          post_t:log(wins_project_quarter_stage)+
          post_t:treat_new:log(wins_project_quarter_stage)+
          post_t|
          0| # no fixed effects
          0| # no IV
          contract_award_unique_key, # clustered at project level
        data=reg_df_subset,
        exactDOF = TRUE,
        cmethod = "reghdfe")

m2=felm(wins_percentage_delay~treat_new+
          log(wins_project_quarter_stage)+
          post_t:treat_new+
          treat_new:log(wins_project_quarter_stage)+
          post_t:log(wins_project_quarter_stage)+
          post_t:treat_new:log(wins_project_quarter_stage)+
          wins_number_of_offers_received+
          log(1+winsorized_initial_budget_i)+
          log(1+winsorized_initial_duration_in_days_i)+
          post_t:log(1+winsorized_initial_budget_i)+
          post_t:log(1+winsorized_initial_duration_in_days_i)+
          post_t:wins_number_of_offers_received+
          post_t|
          0| # no fixed effects
          0| # no IV
          contract_award_unique_key, # clustered at project level
        data=reg_df_subset,
        exactDOF = TRUE,
        cmethod = "reghdfe")

m3=felm(wins_percentage_delay~treat_new+
          log(wins_project_quarter_stage)+
          post_t:treat_new+
          treat_new:log(wins_project_quarter_stage)+
          post_t:log(wins_project_quarter_stage)+
          post_t:treat_new:log(wins_project_quarter_stage)+
          wins_number_of_offers_received+
          log(1+winsorized_initial_budget_i)+
          log(1+winsorized_initial_duration_in_days_i)+
          post_t:log(1+winsorized_initial_budget_i)+
          post_t:log(1+winsorized_initial_duration_in_days_i)+
          post_t:wins_number_of_offers_received|
          action_date_year_quarter| # no fixed effects
          0| # no IV
          contract_award_unique_key, # clustered at project level
        data=reg_df_subset,
        exactDOF = TRUE,
        cmethod = "reghdfe")

m4=felm(wins_percentage_delay~treat_new+
          log(wins_project_quarter_stage)+
          post_t:treat_new+
          treat_new:log(wins_project_quarter_stage)+
          post_t:log(wins_project_quarter_stage)+
          post_t:treat_new:log(wins_project_quarter_stage)+
          wins_number_of_offers_received+
          log(1+winsorized_initial_budget_i)+
          log(1+winsorized_initial_duration_in_days_i)+
          post_t:log(1+winsorized_initial_budget_i)+
          post_t:log(1+winsorized_initial_duration_in_days_i)+
          post_t:wins_number_of_offers_received|
          product_or_service_code+action_date_year_quarter| # no fixed effects
          0| # no IV
          contract_award_unique_key, # clustered at project level
        data=reg_df_subset,
        exactDOF = TRUE,
        cmethod = "reghdfe")

m5=felm(wins_percentage_delay~treat_new+
          log(wins_project_quarter_stage)+
          post_t:treat_new+
          treat_new:log(wins_project_quarter_stage)+
          post_t:log(wins_project_quarter_stage)+
          post_t:treat_new:log(wins_project_quarter_stage)+
          wins_number_of_offers_received+
          log(1+winsorized_initial_budget_i)+
          log(1+winsorized_initial_duration_in_days_i)+
          post_t:log(1+winsorized_initial_budget_i)+
          post_t:log(1+winsorized_initial_duration_in_days_i)+
          post_t:wins_number_of_offers_received|
          product_or_service_code+naics_code+action_date_year_quarter| # no fixed effects
          0| # no IV
          contract_award_unique_key, # clustered at project level
        data=reg_df_subset,
        exactDOF = TRUE,
        cmethod = "reghdfe")

stage_log_regs=stargazer(m2,m3,m4,m5,
          digits=2,
          digits.extra=2,
          title = "Project Stage and QuickPay reform",
          dep.var.labels="$PercentDelay_{it}$  ",
          dep.var.caption = "",
          covariate.labels = c("$Treat_i$",
                               "Log(Stage)",
                               "$Post_t$",
                                "$Treat_i \\times Post_t$",
                               "$Treat_i \\times$ Log(Stage)",
                               "$Post_t \\times$ Log(Stage)",
                               "$Treat_i \\times Post_t \\times$ Log(Stage)",
                               "Constant"),
          object.names=FALSE, 
          model.numbers=TRUE,
          font.size = "small",
          omit.stat=c("f", "ser"),
          column.sep.width = "-2pt",
          add.lines = list(
                           c("Duration, Budget, Bids",rep("No",1),rep("Yes",4)),
                           c("$Post_t \\times $  (Duration, Budget, Bids)",rep("No",1),rep("Yes",4)),                           c("Time fixed effects",rep("No",2),rep("Yes",3)),
                           c("Task fixed effects",rep("No",3),rep("Yes",2)),
                           c("Industry fixed effects",rep("No",4),rep("Yes",1))),
          omit=c('winsorized_initial_duration_in_days_i',
                  'winsorized_initial_budget_i',
                   'wins_number_of_offers_received',
                   'post_t:winsorized_initial_duration_in_days_i',
                   'post_t:winsorized_initial_budget_i',
                   'post_t:wins_number_of_offers_received'),
          table.placement = "H",
          style="default",
          notes=c("Each observation is a project-quarter.",
                  "SEs are robust and clustered at the project level."),
          header=F)
# 
# stage_table_tex=make_tex_pieces(stage_log_regs)
# # Write to file
# write(stage_table_tex,
#       paste0(tables_folder,"/stage_table_tex.tex"))

```